---
title: "Compare OLS, FE, RE, ME models of spatially sampled data"
output: html_document
---


## read data

```{r}

library(ggplot2)
library(tidyverse)
library(broom)
library(dplyr)
library(plyr)
library(rgdal)
library(rgeos)
library(raster)
library(sf)
library(sp)
library(tmap)
library(viridis)
library(spdep)
library(spatialreg)
library(lmtest)
library(Metrics) # for rmse
library(leaflet)
library(leaps) # stepwise model selection

#E:/R-code/Modeling/code/FCN_clean_csvs.R
#~/Documents/R-code
source('E:/R-code/Modeling/code/FCN_clean_csvs.R')
source('E:/R-code/Modeling/code/FCN_plotting.R')
source('E:/R-code/Modeling/code/FCN_sample_data.R')
source('E:/R-code/Modeling/code/FCN_run_model_spatial_sampled.R')

MT_outline <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

onset_type <- 'Gabriel_onset'

median_cell_raw <- read.csv('E:/R-code/Modeling/data/median_onset_cell_v2.csv')
percentile5_cell_raw <- read.csv('E:/R-code/Modeling/data/percentile5_onset_cell_v2.csv')
percentile95_cell_raw <- read.csv('E:/R-code/Modeling/data/percentile95_onset_cell_v2.csv')

grid_1deg <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/grid_1deg', layer = 'grid_1deg')
munis <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/munis', layer = 'munis_SHP')
crs(munis) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
  
cell_sf <- st_read(dsn = 'E:/R-code/Modeling/data/shp/median_onset_cell', layer = 'median_onset_cell_SHP')

min_soy_area <- 2 #km2. min area of total or SC/DC soy in cell, muni or property to be considered in model

```

## read and clean spatial data

```{r}

# CSV DATA -----------------------------------------------------------------------------------------------------------------
# median cell
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                    rename_cols_median_cell()

median_cell$plant_stat_type <- rep('median', nrow(median_cell))


# percentiles
percentile5_cell <- percentile5_cell_raw %>% rename_cols_percentile_cell()
percentile95_cell <- percentile95_cell_raw %>% rename_cols_percentile_cell()

# SF DATA ------------------------------------------------------------------------------------------------

# get cell_ID column for median
cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)

# join median, percentile data to cell_sf
# cell_sf has median information, but copy it and put in percentile info for DC and SC plant

cell_sf$plant_stat_type <- rep("median", nrow(cell_sf))

cell_sf_percentile5 <- cell_sf
cell_sf_percentile5$SC_plant <- percentile5_cell$SC_plant
cell_sf_percentile5$DC_plant <- percentile5_cell$DC_plant
cell_sf_percentile5$plant_stat_type <- rep("percentile5", nrow(cell_sf_percentile5))

cell_sf_percentile95 <- cell_sf
cell_sf_percentile95$SC_plant <- percentile95_cell$SC_plant
cell_sf_percentile95$DC_plant <- percentile95_cell$DC_plant
cell_sf_percentile95$plant_stat_type <- rep("percentile95", nrow(cell_sf_percentile95))

cell_sf <- rbind(cell_sf, cell_sf_percentile5, cell_sf_percentile95)

cell_sf_tidy <- cell_sf %>% tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_harvest, DC_harvest)) %>%
            categorize_regions_cell_sf_tidy() # categorize cells into four regions

cell_sf_tidy$year_index <- cell_sf_tidy$year - 2003
cell_sf_tidy$year_factor <- as.factor(cell_sf_tidy$year)

cell_sf_tidy <- cell_sf_tidy %>%  drop_na
cell_sf_tidy$delay <- cell_sf_tidy$plant - cell_sf_tidy$onset

# label which cells were planted before onset and filter for only before onset
cell_sf_tidy$beforeonset <- ifelse(cell_sf_tidy$onset > cell_sf_tidy$plant, 1, 0)
cell_sf_tidy <-  cell_sf_tidy[cell_sf_tidy$beforeonset == 0,]

# split into SC and DC cells
cell_sf_tidy_SC <- cell_sf_tidy[cell_sf_tidy$intensity == "SC",]
cell_sf_tidy_DC <- cell_sf_tidy[cell_sf_tidy$intensity == "DC",]
```

## OLS

```{r}

plant_stat_types <- c("median", "percentile5", "percentile95")

# set up data frame to store model results for all models
ols_results <- data.frame(plant_stat_type = numeric(0),
                      intensity = numeric(0),
                      model_type = numeric(0),
                      onset_coef = numeric(0),
                      onset_std_err = numeric(0),
                      year_treatment = character(0),
                      lat_treatment = character(0),
                      region_treatment = character(0),
                      cell_treatment = character(0),
                      model_type = character(0))

for (plant_stat_type in plant_stat_types) {

  print(plant_stat_type)
  SC_output <- run_OLS(full_data = cell_sf_tidy_SC,
                        predictors = c("onset",
                          "lat", "lon", "region", # for spatial effects
                          "year_index" # for time effects
                          ),
                    y.var = "plant", plant_stat = plant_stat_type,
                    grid_size = 0.75, lat_offset = 0, lon_offset = 0, agg_scheme = FALSE,
                    plot_samples = FALSE, plot_model_evals = FALSE,
                    year_oi = 2012, do_elim_year = FALSE,
                    chosen_intensity = "SC")
  
  DC_output <- run_OLS(full_data = cell_sf_tidy_DC,
                        predictors = c("onset",
                          "lat", "lon", "region", # for spatial effects
                          "year_index" # for time effects
                          ),
                    y.var = "plant", plant_stat = plant_stat_type,
                    grid_size = 0.75, lat_offset = 0, lon_offset = 0, agg_scheme = FALSE,
                    plot_samples = FALSE, plot_model_evals = FALSE,
                    year_oi = 2012, do_elim_year = FALSE,
                    chosen_intensity = "DC")
    
  print(c(plant_stat_type, "SC", "OLS", as.numeric(SC_output$onset_coef), as.numeric(SC_output$onset_std_err)))
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("OLS", "OLS"),
                                onset_coef = c(as.numeric(SC_output$onset_coef), as.numeric(DC_output$onset_coef)),
                                onset_std_err = c(as.numeric(SC_output$onset_std_err), as.numeric(DC_output$onset_std_err)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('reg', 'reg'),
                                cell_treatment = c('none', 'none'))
  ols_results <- rbind(ols_results, updated_results)
}

print(ols_results)

```


## FE model
```{r}
library(plm) # for FE and FE

# sample from full data and turn into data frame
sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = "median", grid_size = 0.75,
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_SC) <- NULL

sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = "median", grid_size = 0.75,
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_DC) <- NULL

# for plm, first set data as panel data
panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID","year_index"))
panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID","year_index"))

# FE
fe_result_SC <- plm(plant ~ onset + lat + lon + region, data = panel_SC, model = "within")
fe_result_DC <- plm(plant ~ onset + lat + lon + region, data = panel_DC, model = "within")

print(fe_result_SC)
print(fe_result_DC)

# set up data frame to store model results for all models
fe_results <- data.frame(plant_stat_type = numeric(0),
                      intensity = numeric(0),
                      model_type = numeric(0),
                      onset_coef = numeric(0),
                      onset_std_err = numeric(0),
                      year_treatment = character(0),
                      lat_treatment = character(0),
                      region_treatment = character(0),
                      cell_treatment = character(0),
                      model_type = character(0))

############# model for (1) cell_ID and year_index as FE in panel, (2) onset as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID","year_index")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID","year_index")) 

  SC_output <- plm(plant ~ onset, data = panel_SC, model = "within")
  DC_output <- plm(plant ~ onset, data = panel_DC, model = "within")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("FE", "FE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('panel', 'panel'),
                                lat_treatment = c('none', 'none'),
                                region_treatment = c('none', 'none'),
                                cell_treatment = c('panel', 'panel'))
  fe_results <- rbind(fe_results, updated_results)
}

############# model for (1) cell_ID and year_index as FE in panel, (2) onset and year_index as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID", "year_index")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID", "year_index")) 

  SC_output <- plm(plant ~ onset + year_index, data = panel_SC, model = "within")
  DC_output <- plm(plant ~ onset + year_index, data = panel_DC, model = "within")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("FE", "FE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('panel_reg', 'panel_reg'),
                                lat_treatment = c('none', 'none'),
                                region_treatment = c('none', 'none'),
                                cell_treatment = c('panel', 'panel'))
  fe_results <- rbind(fe_results, updated_results)
}

############# model for (1) cell_ID as FE in panel, (2) onset and year_index as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID")) 

  SC_output <- plm(plant ~ onset + year_index, data = panel_SC, model = "within")
  DC_output <- plm(plant ~ onset + year_index, data = panel_DC, model = "within")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("FE", "FE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('none', 'none'),
                                region_treatment = c('none', 'none'),
                                cell_treatment = c('panel', 'panel'))
  fe_results <- rbind(fe_results, updated_results)
}

print(fe_results)
```

## RE model

```{r}
library(plm) # for FE and FE

# sample from full data and turn into data frame
sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = "median", grid_size = 0.75,
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_SC) <- NULL

sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = "median", grid_size = 0.75,
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_DC) <- NULL

# for plm, first set data as panel data
panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID", "year_index"))
panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID", "year_index"))

# FE
re_result_SC <- plm(plant ~ onset + lat + region + year_index, data = panel_SC, model = "random")
re_result_DC <- plm(plant ~ onset + lat + region + year_index, data = panel_DC, model = "random")

print(re_result_SC)
print(re_result_DC)

# set up data frame to store model results for all models
re_results <- data.frame(plant_stat_type = numeric(0),
                      intensity = numeric(0),
                      model_type = numeric(0),
                      onset_coef = numeric(0),
                      onset_std_err = numeric(0),
                      year_treatment = character(0),
                      lat_treatment = character(0),
                      region_treatment = character(0),
                      cell_treatment = character(0),
                      model_type = character(0))

############# model for (1) cell_ID and year_index as FE in panel, (2) onset, region, lat as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID","year_index")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID","year_index")) 

  SC_output <- plm(plant ~ onset + lat + region, data = panel_SC, model = "random")
  DC_output <- plm(plant ~ onset + lat + region, data = panel_DC, model = "random")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("RE", "RE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('panel', 'panel'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('reg', 'reg'),
                                cell_treatment = c('panel', 'panel'))
  re_results <- rbind(re_results, updated_results)
}

############# model for (1) cell_ID and year_index as FE in panel, (2) onset, region, lat, year_index as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID","year_index")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID","year_index")) 

  SC_output <- plm(plant ~ onset + lat + region + year_index, data = panel_SC, model = "random")
  DC_output <- plm(plant ~ onset + lat + region + year_index, data = panel_DC, model = "random")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("RE", "RE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('panel_reg', 'panel_reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('reg', 'reg'),
                                cell_treatment = c('panel', 'panel'))
  re_results <- rbind(re_results, updated_results)
}

############# model for (1) cell_ID as FE in panel, (2) onset, region, lat, year_index as predictor ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  panel_SC <- pdata.frame(sampled_SC,index = c("cell_ID")) 
  panel_DC <- pdata.frame(sampled_DC,index = c("cell_ID")) 

  SC_output <- plm(plant ~ onset + lat + region + year_index, data = panel_SC, model = "random")
  DC_output <- plm(plant ~ onset + lat + region + year_index, data = panel_DC, model = "random")
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("RE", "RE"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('reg', 'reg'),
                                cell_treatment = c('panel', 'panel'))
  re_results <- rbind(re_results, updated_results)
}

print(re_results)
```

## ME model

```{r}

library(lme4) # for lmer()
library(nlme) # for lme()

# sample from full data and turn into data frame
# sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = "median", grid_size = 0.75,
#                  lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
# st_geometry(sampled_SC) <- NULL
# 
# sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = "median", grid_size = 0.75,
#                  lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
# st_geometry(sampled_DC) <- NULL
# 
# # ME
# me_result_SC <- lmer(plant ~ onset + year_index + (1|cell_ID), data = sampled_SC)
# me_result_DC <- lmer(plant ~ onset + year_index + (1|cell_ID), data = sampled_DC)
# 
# print(me_result_SC)
# print(me_result_DC)
#
# # another ME. do nested models to look at effect of additional random effects
# me2_result_SC <- lmer(plant ~ onset + year_index + (1|lat), data = sampled_SC, REML = FALSE)
# me3_result_SC <- lmer(plant ~ onset + year_index + (1|region) + (1|cell_ID), data = sampled_SC, REML = FALSE)
# anova(me2_result_SC, me3_result_SC)

# another ME
#me2_result_SC <- lme(plant ~ onset + year_index, random = ~1|, data = sampled_SC, method = "ML")
#me2_complex_result_SC <- lme(plant ~ onset + year_index, random = ~1|cell_ID, data = sampled_SC, method = "ML")
#anova(me2_result_SC, me2_complex_result_SC)

# set up data frame to store model results for all models
me_results <- data.frame(plant_stat_type = numeric(0),
                      intensity = numeric(0),
                      model_type = numeric(0),
                      onset_coef = numeric(0),
                      onset_std_err = numeric(0),
                      year_treatment = character(0),
                      lat_treatment = character(0),
                      region_treatment = character(0),
                      cell_treatment = character(0),
                      model_type = character(0))

############# model for (1) FE: onset, year, lat, region (2) RE: cell_ID ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  SC_output <- lmer(plant ~ onset + year_index + lat + region + (1|cell_ID), data = sampled_SC)
  DC_output <- lmer(plant ~ onset + year_index + lat + region + (1|cell_ID), data = sampled_DC)
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("ME", "ME"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('reg', 'reg'),
                                cell_treatment = c('RE', 'RE'))
  me_results <- rbind(me_results, updated_results)
}

############# model for (1) FE: onset, year, lat (2) RE: cell_ID, region ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  SC_output <- lmer(plant ~ onset + year_index + lat + (1|region) + (1|cell_ID), data = sampled_SC)
  DC_output <- lmer(plant ~ onset + year_index + lat + (1|region) + (1|cell_ID), data = sampled_DC)
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("ME", "ME"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('RE', 'RE'),
                                cell_treatment = c('RE', 'RE'))
  me_results <- rbind(me_results, updated_results)
}

############# model for (1) FE: onset, year, lat (2) RE: region ####################################
for (plant_stat_type in plant_stat_types) {
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  SC_output <- lmer(plant ~ onset + year_index + lat + (1|region), data = sampled_SC)
  DC_output <- lmer(plant ~ onset + year_index + lat + (1|region), data = sampled_DC)
  
  SC_onset <- summary(SC_output)$coefficients['onset',]['Estimate']
  SC_onset_stderr <- summary(SC_output)$coefficients['onset',]['Std. Error']
  DC_onset <- summary(DC_output)$coefficients['onset',]['Estimate']
  DC_onset_stderr <- summary(DC_output)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = c(plant_stat_type, plant_stat_type),
                                intensity = c("SC", "DC"),
                                model_type = c("ME", "ME"),
                                onset_coef = c(as.numeric(SC_onset), as.numeric(DC_onset)),
                                onset_std_err = c(as.numeric(SC_onset_stderr), as.numeric(DC_onset_stderr)),
                                year_treatment = c('reg', 'reg'),
                                lat_treatment = c('reg', 'reg'),
                                region_treatment = c('RE', 'RE'),
                                cell_treatment = c('none', 'none'))
  me_results <- rbind(me_results, updated_results)
}

print(me_results)
```

## combine onset coef results and plot

```{r}

results <- rbind(ols_results, fe_results, re_results, me_results)

for (plant_stat_type in plant_stat_types) {
  for (intensity in c("SC", "DC")) {
    
    data <- results[results$intensity == intensity & results$plant_stat_type == plant_stat_type,]
    data_names <- c("OLS", "FE\nyear:\npanel", "FE\nyear:\npanel+reg", "FE\nyear:\nreg", # FE
                    "RE\nyear:\npanel", "RE\nyear:\npanel+reg", "RE\nyear:\nreg", # RE
                    "ME\nregion:\nreg\ncell:\nRE", "ME\nregion:\nRE\ncell:\nRE", "ME\nregion:\nRE\ncell:\nnone")
    data$model_type_specific <- data_names
    print(data)
    onset_plot <- ggplot(data = data, aes(x = model_type_specific)) +
      geom_point(aes(y = onset_coef, col = model_type)) +
      geom_errorbar(aes(ymin=onset_coef-onset_std_err, ymax=onset_coef+onset_std_err, col = model_type)) +
      theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
      ggtitle(paste('onset coef,', intensity, plant_stat_type)) +
      ylim(c(-0.2, 0.7)) +
      theme_bw()
    
    print(onset_plot)
  }
}
```

## try variations within ME

```{r}

# set up data frame to store model results for all models
me_results2 <- data.frame(plant_stat_type = numeric(0),
                      intensity = numeric(0),
                      model_type = numeric(0),
                      onset_coef = numeric(0),
                      onset_std_err = numeric(0),
                      year_treatment = character(0),
                      lat_treatment = character(0),
                      region_treatment = character(0),
                      cell_treatment = character(0),
                      model_type_specific = character(0))

############# model for different MEs, where the RE changes ####################################
for (plant_stat_type in plant_stat_types) {
  
  # for each plant stat type, try:
  # (1) region as RE
  # (2) lat as RE
  # (3) year as RE
  # (4) region + lat as RE
  # (5) region + year as RE
  # (6) lat + year as RE
  # (7) region + lat + year as RE
  
  sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = plant_stat_type, grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_SC) <- NULL
  
  sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = plant_stat_type, grid_size = 0.75, 
                   lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
  st_geometry(sampled_DC) <- NULL

  # (1) region as RE
  SC_output_RE_region <- lmer(plant ~ onset + year_index + lat + (1|region), data = sampled_SC)
  DC_output_RE_region <- lmer(plant ~ onset + year_index + lat + (1|region), data = sampled_DC)
  
  SC_onset_RE_region <- summary(SC_output_RE_region)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_region <- summary(SC_output_RE_region)$coefficients['onset',]['Std. Error']
  DC_onset_RE_region <- summary(DC_output_RE_region)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_region <- summary(DC_output_RE_region)$coefficients['onset',]['Std. Error']
  
  # (2) lat as RE
  SC_output_RE_lat <- lmer(plant ~ onset + year_index + region + (1|lat), data = sampled_SC)
  DC_output_RE_lat <- lmer(plant ~ onset + year_index + region + (1|lat), data = sampled_DC)
  
  SC_onset_RE_lat <- summary(SC_output_RE_lat)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_lat <- summary(SC_output_RE_lat)$coefficients['onset',]['Std. Error']
  DC_onset_RE_lat <- summary(DC_output_RE_lat)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_lat <- summary(DC_output_RE_lat)$coefficients['onset',]['Std. Error']
  
  # (3) year as RE
  SC_output_RE_year <- lmer(plant ~ onset + lat + region + (1|year_index), data = sampled_SC)
  DC_output_RE_year <- lmer(plant ~ onset + lat + region + (1|year_index), data = sampled_DC)

  SC_onset_RE_year <- summary(SC_output_RE_year)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_year <- summary(SC_output_RE_year)$coefficients['onset',]['Std. Error']
  DC_onset_RE_year <- summary(DC_output_RE_year)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_year <- summary(DC_output_RE_year)$coefficients['onset',]['Std. Error']
  
  # (4) region + lat as RE
  SC_output_RE_region_lat <- lmer(plant ~ onset + year_index + (1|lat) + (1|region), data = sampled_SC)
  DC_output_RE_region_lat <- lmer(plant ~ onset + year_index + (1|lat) + (1|region), data = sampled_DC)
  
  SC_onset_RE_region_lat <- summary(SC_output_RE_region_lat)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_region_lat <- summary(SC_output_RE_region_lat)$coefficients['onset',]['Std. Error']
  DC_onset_RE_region_lat<- summary(DC_output_RE_region_lat)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_region_lat <- summary(DC_output_RE_region_lat)$coefficients['onset',]['Std. Error']
  
  # (5) region + year as RE
  SC_output_RE_region_year <- lmer(plant ~ onset + (1|year_index) + lat + (1|region), data = sampled_SC)
  DC_output_RE_region_year <- lmer(plant ~ onset + (1|year_index) + lat + (1|region), data = sampled_DC)
  
  SC_onset_RE_region_year <- summary(SC_output_RE_region_year)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_region_year <- summary(SC_output_RE_region_year)$coefficients['onset',]['Std. Error']
  DC_onset_RE_region_year <- summary(DC_output_RE_region_year)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_region_year <- summary(DC_output_RE_region_year)$coefficients['onset',]['Std. Error']
  
  # (6) lat + year as RE
  SC_output_RE_lat_year <- lmer(plant ~ onset + (1|year_index) + region + (1|lat), data = sampled_SC)
  DC_output_RE_lat_year <- lmer(plant ~ onset + (1|year_index) + region + (1|lat), data = sampled_DC)
  
  SC_onset_RE_lat_year <- summary(SC_output_RE_lat_year)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_lat_year <- summary(SC_output_RE_lat_year)$coefficients['onset',]['Std. Error']
  DC_onset_RE_lat_year <- summary(DC_output_RE_lat_year)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_lat_year <- summary(DC_output_RE_lat_year)$coefficients['onset',]['Std. Error']
  
  # (7) region + lat + year as RE
  SC_output_RE_region_lat_year <- lmer(plant ~ onset + (1|year_index) + (1|region) + (1|lat), data = sampled_SC)
  DC_output_RE_region_lat_year <- lmer(plant ~ onset + (1|year_index) + (1|region) + (1|lat), data = sampled_DC)
  
  SC_onset_RE_region_lat_year <- summary(SC_output_RE_region_lat_year)$coefficients['onset',]['Estimate']
  SC_onset_stderr_RE_region_lat_year <- summary(SC_output_RE_region_lat_year)$coefficients['onset',]['Std. Error']
  DC_onset_RE_region_lat_year <- summary(DC_output_RE_region_lat_year)$coefficients['onset',]['Estimate']
  DC_onset_stderr_RE_region_lat_year <- summary(DC_output_RE_region_lat_year)$coefficients['onset',]['Std. Error']
  
  updated_results <- data.frame(plant_stat_type = rep(plant_stat_type, 14), #c(plant_stat_type, plant_stat_type),
                                intensity = rep(c("SC", "DC"), 7),
                                model_type_specific = c("RE:\nregion", "RE:\nregion", # (1) region as RE
                                                        "RE:\nlat", "RE:\nlat", # (2) lat as RE
                                                        "RE:\nyear", "RE:\nyear", # (3) year as RE
                                                        "RE:\nregion\nlat", "RE:\nregion\nlat", # (4) region + lat as RE
                                                        "RE:\nregion\nyear", "RE:\nregion\nyear",  # (5) region + year as RE
                                                        "RE:\nlat\nyear", "RE:\nlat\nyear", # (6) lat + year as RE
                                                        "RE:\nregion\nlat\nyear", "RE:\nregion\nlat\nyear"), # (7) region + lat + year as RE
                                onset_coef = c(as.numeric(SC_onset_RE_region), as.numeric(DC_onset_RE_region), # (1) region as RE
                                               as.numeric(SC_onset_RE_lat), as.numeric(DC_onset_RE_lat), # (2) lat as RE
                                               as.numeric(SC_onset_RE_year), as.numeric(DC_onset_RE_year), # (3) year as RE
                                               as.numeric(SC_onset_RE_region_lat), as.numeric(DC_onset_RE_region_lat), # (4) region + lat as RE
                                               as.numeric(SC_onset_RE_region_year), as.numeric(DC_onset_RE_region_year), # (5) region + year as RE
                                               as.numeric(SC_onset_RE_lat_year), as.numeric(DC_onset_RE_lat_year), # (6) lat + year as RE
                                               as.numeric(SC_onset_RE_region_lat_year), as.numeric(DC_onset_RE_region_lat_year) # (7) region + lat + year as RE
                                               ),
                                onset_std_err = c(as.numeric(SC_onset_stderr_RE_region), as.numeric(DC_onset_stderr_RE_region), # (1) region as RE
                                               as.numeric(SC_onset_stderr_RE_lat), as.numeric(DC_onset_stderr_RE_lat), # (2) lat as RE
                                               as.numeric(SC_onset_stderr_RE_year), as.numeric(DC_onset_stderr_RE_year), # (3) year as RE
                                               as.numeric(SC_onset_stderr_RE_region_lat), as.numeric(DC_onset_stderr_RE_region_lat), # (4) region + lat as RE
                                               as.numeric(SC_onset_stderr_RE_region_year), as.numeric(DC_onset_stderr_RE_region_year), # (5) region + year as RE
                                               as.numeric(SC_onset_stderr_RE_lat_year), as.numeric(DC_onset_stderr_RE_lat_year), # (6) lat + year as RE
                                               as.numeric(SC_onset_stderr_RE_region_lat_year), as.numeric(DC_onset_stderr_RE_region_lat_year) # (7) region + lat + year as RE),
                                )
)
  me_results2 <- rbind(me_results2, updated_results)
}

for (plant_stat_type in plant_stat_types) {
  for (intensity in c("SC", "DC")) {
    
    data <- me_results2[me_results2$intensity == intensity & me_results2$plant_stat_type == plant_stat_type,]
    
    onset_plot <- ggplot(data = data, aes(x = model_type_specific)) +
      geom_point(aes(y = onset_coef)) +
      geom_errorbar(aes(ymin=onset_coef-onset_std_err, ymax=onset_coef+onset_std_err)) +
      theme(axis.text.y = element_blank(), axis.ticks = element_blank()) +
      ggtitle(paste('Mixed effects onset coef,', intensity, plant_stat_type)) +
      ylim(c(-0.2, 0.7)) +
      theme_bw()
    
    print(onset_plot)
  }
}

print(me_results2)

```

## testing ME specifications

```{r}
sampled_SC <- get_sampled_data(full_data = cell_sf_tidy_SC, plant_stat = "median", grid_size = 0.75, 
                 lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_SC) <- NULL
  
sampled_DC <- get_sampled_data(full_data = cell_sf_tidy_DC, plant_stat = "median", grid_size = 0.75, 
                  lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, plot_samples = FALSE, year_oi = 2012)
st_geometry(sampled_DC) <- NULL

simple_model <- lmer(plant ~ onset + lat + (1|region) + year_index, data = sampled_DC, REML = FALSE)
complex_model <- lmer(plant ~ onset + (1|lat) + (1|region) + (1|year_index), data = sampled_DC, REML = FALSE)

anova(simple_model, complex_model)

summary(simple_model)
summary(complex_model)

ols_model <- lm(plant ~ onset + lat + region + year_index, data = sampled_DC)
  
```

## look at correlations between onset and other predictors

```{r}

all_DC_median <- cell_sf_tidy_DC[cell_sf_tidy_DC$plant_stat_type == "median",]

plot(all_DC_median$onset, all_DC_median$lat)

plot(all_DC_median$onset, all_DC_median$year_index)

ggplot(data = all_DC_median, aes(x = region, y = onset)) +
  geom_violin() +
  stat_summary(fun.y=median, geom="point", size=2, color="red") +
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  theme_bw() +
  facet_wrap( ~ year)

ggplot(data = all_DC_median, aes(x = region, y = plant)) +
  geom_violin() +
  stat_summary(fun.y=median, geom="point", size=2, color="red") +
  #geom_dotplot(binaxis='y', stackdir='center', dotsize=1) +
  theme_bw() +
  facet_wrap( ~ year)

print(cor(all_DC_median$onset, all_DC_median$year_index))
print(cor(all_DC_median$onset, all_DC_median$lat))
```
## tests to compare models

```{r}


# FE vs OLS # if p value is small, have significant effects and use FE
print('FE vs OLS')
pFtest(fe_result_SC, ols_result_SC)
pFtest(fe_result_DC, ols_result_DC)

# RE vs OLS # if p value is small, have significant effects and use RE
print('RE vs OLS')
plmtest(ols_result_SC)
plmtest(ols_result_DC) 

# RE vs FE # if p value is small, one model is inconsistent, so do FE. Hausman test
print('RE vs FE')
phtest(re_result_SC, fe_result_SC)
phtest(re_result_DC, fe_result_DC)

# ME vs FE
print('ME vs FE')
anova(me_result_SC, fe_result_DC)
anova(me_result_DC, fe_result_DC)
```