---
title: "Random forest and OLS"
output: html_document
---

1. Sample cells at 100km distance to skip spatial autocorrelation
2. Regular OLS
3. Model evaluation.
4. Repeat above for consistency

## read data

```{r}

library(ggplot2)
library(tidyverse)
library(broom)
library(dplyr)
library(rgdal)
library(rgeos)
library(raster)
library(sf)
library(sp)
library(tmap)
library(viridis)
library(spdep)
library(spatialreg)
library(lmtest)
library(Metrics) # for rmse
library(leaflet)
library(leaps) # stepwise model selection

# random forest, decision tree
library(randomForest)
library(rpart)
library(caret)

#E:/R-code/Modeling/code/FCN_clean_csvs.R
#~/Documents/R-code
source('E:/R-code2/Modeling/code/FCN_clean_csvs.R')
source('E:/R-code2/Modeling/code/FCN_plotting.R')
source('E:/R-code2/Modeling/code/FCN_sample_data.R')
source('E:/R-code2/Modeling/code/FCN_run_model_spatial_sampled.R')
source('E:/R-code2/Modeling/code/FCN_predictionError_ML.R')

onset_type <- 'Gabriel_onset' #'AA_25_chirps_ATchirps5km' # 'Gabriel_onset'

if (onset_type != 'Gabriel_onset') {
  filename_median <- paste0('E:/R-code-large-files/data_onset_', onset_type, '/median_onset_cell_', onset_type, '.csv')
  filename_percentile5 <- paste0('E:/R-code-large-files/data_onset_', onset_type, '/percentile5_onset_cell_', onset_type, '.csv')
  filename_percentile25 <- paste0('E:/R-code-large-files/data_onset_', onset_type, '/percentile25_onset_cell_', onset_type, '.csv')

  filename_shp<- paste0('E:/R-code-large-files/data_onset_', onset_type, '/shp')
  layername_shp <- paste0('median_onset_cell_SHP_', onset_type)
  
  median_cell_raw <- read.csv(filename_median)
  percentile5_cell_raw <- read.csv(filename_percentile5)
  percentile25_cell_raw <- read.csv(filename_percentile25)
  
  cell_sf <- st_read(dsn = filename_shp, layer = layername_shp)
}

if (onset_type == 'Gabriel_onset') {
  median_cell_raw <- read.csv('E:/R-code2/Modeling/data/median_onset_cell_v3.csv')
  percentile5_cell_raw <- read.csv('E:/R-code2/Modeling/data/percentile5_onset_cell_v3.csv')
  percentile25_cell_raw <- read.csv('E:/R-code2/Modeling/data/percentile25_onset_cell_v3.csv')
  
  cell_sf <- st_read(dsn = 'E:/R-code2/Modeling/data/shp/median_onset_cell_v3', layer = 'median_onset_cell_SHP_v3')
}


MT_outline <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

grid_1deg <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/grid_1deg', layer = 'grid_1deg')
munis <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/munis', layer = 'munis_SHP')
crs(munis) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

# read in all the onsets. only the csv, not shp
all_onset_types <- c('Gabriel_onset', 'AA_2_persiann', 'AA_3_persiann', 
                      'AA_25_persiann', 'AA_25_chirps_ATgabriel25km', 'AA_25_persiann_ATgabriel25km',
                     'freq_5_persiann', 'freq_8_persiann', 'freq_10_persiann', 'freq_12_persiann',
                     'monsoon_30_persiann', 'monsoon_40_persiann',
                     'pentad_8_persiann', 'pentad_10_persiann', 'pentad_15_persiann',
                     'rangethres_10_15_15_30_persiann', 'rangethres_10_15_15_40_persiann',
                     'rangethres_10_15_20_20_persiann', 'rangethres_10_15_20_30_persiann',
                     'rangethres_10_15_30_40_persiann', 'thres_10_persiann')
# didn't do:  'AA_25_chirps_ATchirps5km'

```

## read and clean spatial data

```{r}

# CSV DATA -----------------------------------------------------------------------------------------------------------------
# median cell
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                    rename_cols_median_cell()
median_cell$plant_stat_type <- rep('median', nrow(median_cell))


# percentiles
percentile5_cell <- percentile5_cell_raw %>% rename_cols_percentile_cell()
percentile25_cell <- percentile25_cell_raw %>% rename_cols_percentile_cell()

# SF DATA ------------------------------------------------------------------------------------------------

# get cell_ID column for median
cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)

# join median, percentile data to cell_sf
# cell_sf has median information, but copy it and put in percentile info for DC and SC plant

cell_sf$plant_stat_type <- rep("median", nrow(cell_sf))

cell_sf_percentile5 <- cell_sf
cell_sf_percentile5$SC_plant <- percentile5_cell$SC_plant
cell_sf_percentile5$DC_plant <- percentile5_cell$DC_plant
cell_sf_percentile5$plant_stat_type <- rep("percentile5", nrow(cell_sf_percentile5))

cell_sf_percentile25 <- cell_sf
cell_sf_percentile25$SC_plant <- percentile25_cell$SC_plant
cell_sf_percentile25$DC_plant <- percentile25_cell$DC_plant
cell_sf_percentile25$plant_stat_type <- rep("percentile25", nrow(cell_sf_percentile25))

cell_sf <- rbind(cell_sf, cell_sf_percentile5, cell_sf_percentile25)

cell_sf_tidy <- cell_sf %>% tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_harvest, DC_harvest)) %>%
            categorize_regions_cell_sf_tidy() # categorize cells into four regions

cell_sf_tidy$year_index <- cell_sf_tidy$year - 2003
cell_sf_tidy$year_factor <- as.factor(cell_sf_tidy$year)

cell_sf_tidy <- cell_sf_tidy %>%  drop_na
cell_sf_tidy$delay <- cell_sf_tidy$plant - cell_sf_tidy$onset

# plotting
year <- 2013
cell_year <- cell_sf_tidy[cell_sf_tidy$year == year, ]
  
onset_map <- ggplot(cell_year) +
  geom_sf(aes(fill = onset)) +
  scale_fill_viridis() +
  ggtitle(paste("Onset for spatial sampling", year, onset_type)) +
  geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", alpha = 0, linetype = 1) +
  theme_bw()

#print(onset_map)
  
```


```{r}

do_elimcell <- TRUE
do_elimyear <- TRUE
cell_reducer <- 10 # the number of cells by this when NOT sampling data and doing elimcell
sample_grid_size <- 0.75

set.seed(100)
wanted_variables <- c('year', 'lat', 'lon', 'onset', 'region', 'intensity', 'plant', 'cell_ID')
wanted_predictors <- c('year', 'lat', 'lon', 'onset', 'region', 'intensity')
f <- as.formula(paste('plant ~', paste(wanted_predictors, collapse = " + ")))

wanted_plant_stat <- "percentile5"

# to store prediction results
prediction_error_results <- data.frame(model_type = character(0),
                                      elim_type = character(0),
                                      elim_year = numeric(0),
                                      elim_cell = character(0),
                                      rmse = numeric(0),
                                      error = numeric(0),
                                      sampled_data = character(0),
                                      fit_bias = numeric(0)) # the slope betweeen the observed plant and fitted value)

for (sample_data in c(TRUE)) { # sampling data means the number of data points is reduced
  # prepare data. cell_df has the sampled data with appropriate plant_stat, and cell_sf adds the geometry
  if (sample_data) {
    sampled_data <- get_sampled_data(full_data = cell_sf_tidy, plant_stat = wanted_plant_stat, grid_size = sample_grid_size, 
                                     lat_offset = 0, lon_offset = 0, agg_scheme = FALSE, 
                                     plot_samples = FALSE, year_oi = 2008)
    cell_sf <- sampled_data
    cell_df <- sampled_data
    st_geometry(cell_df) <- NULL
  }
  
  if (!sample_data) {
    cell_sf <- cell_sf_tidy
    cell_df <- cell_sf_tidy
    st_geometry(cell_df) <- NULL
  }
  
  cell_df <- cell_df[cell_df$plant_stat_type == wanted_plant_stat, wanted_variables]
  cell_df$intensity <- as.factor(cell_df$intensity)
  cell_df$region <- as.factor(cell_df$region)
  cell_sf <- cell_sf[cell_sf$plant_stat_type == wanted_plant_stat, wanted_variables]
  
  # random forest: regular validaton, 30% randomly eliminated  ----------------------------------------------
  # split into train and validation sets for 30% validation
  train_indeces <- sample(nrow(cell_df), 0.7*nrow(cell_df), replace = FALSE)
  train <- cell_df[train_indeces,]
  valid <- cell_df[-train_indeces,]
  
  rf_model1 <- randomForest(f, data = train, importance = TRUE, ntree = 600, mtry = 2)
  valid$rf_predicted_plant <- predict(rf_model1, valid)
  plot(valid$plant, valid$rf_predicted_plant, main = 'rf')
  abline(a = 0, b = 1)

  importance(rf_model1)
  varImpPlot(rf_model1)

  rf_rmse <- rmse(valid$plant, valid$rf_predicted_plant)
  rf_error <- mean(valid$rf_predicted_plant - valid$plant)
  
  # save
  prediction_error_results <- rbind(prediction_error_results,
                                    
                                data.frame(model_type = c('rf'),
                                           elim_type = c('30%'),
                                           elim_year = c(NA),
                                           elim_cell = c(NA),
                                           rmse = c(rf_rmse),
                                           error = c(rf_error),
                                           sampled_data = c(sample_data),
                                           fit_bias = c(NA)))
  
  # random forest : fit on all data, then predict on training data -------------------------------------------
  # save residual and observed
  rf_model2 <- randomForest(f, data = cell_df, importance = TRUE, ntree = 600, mtry = 2)
  residuals <- cell_df$plant - predict(rf_model1, valid)
  error_df <- data.frame(residual = residuals,
                         observed = cell_df$plant)
  
  # model residual vs observed, look at slope as measure of bias
  error_model <- lm(residual ~ observed, data = error_df)
  bias_measure <- error_model$coefficients['observed']
  
  plot(error_df$observed, error_df$residual, main = 'rf, trained on all data')
  plot(cell_df$onset, error_df$residual, main = 'rf, trained on all data')
  plot(cell_df$year, error_df$residual, main = 'rf, trained on all data')
  plot(cell_df$lat, error_df$residual, main = 'rf, trained on all data')
  plot(cell_df$lon, error_df$residual, main = 'rf, trained on all data')
  
   # save
  prediction_error_results <- rbind(prediction_error_results,
                                    
                                data.frame(model_type = c('rf'),
                                           elim_type = c('none'),
                                           elim_year = c(NA),
                                           elim_cell = c(NA),
                                           rmse = c(NA),
                                           error = c(NA),
                                           sampled_data = c(sample_data),
                                           fit_bias = c(bias_measure)))

  
  # random forest: eliminate year ---------------------------------------------------------------------------
  if (do_elimyear) {
    for (elim_year in 2004:2014) {
      result <- test_elimyear(elim_year, cell_df, cell_sf, f, "rf")
  
      prediction_error_results <- rbind(prediction_error_results,
  
                                  data.frame(model_type = c('rf'),
                                             elim_type = c('year'),
                                             elim_year = c(elim_year),
                                             elim_cell = c(NA),
                                             rmse = c(result$rmse_elimyear),
                                             error = c(result$error_elimyear),
                                             sampled_data = c(sample_data),
                                             fit_bias = c(NA)))
      #print(result)
    }
  }

  # random forest: eliminate cell -------------------------------------------------------------------------
  unique_cells <- unique(cell_df[cell_df$year == 2004, "cell_ID"])
  if (!sample_data) {
    chosen_cells <- sample(unique_cells, length(unique_cells)/cell_reducer, replace = FALSE) # randomly select some unique cells, otherwise too much data
  }
  if (sample_data) {
    chosen_cells <- unique_cells
  }
  cell_sf_elimcell <- cell_sf[cell_sf$year == 2004 & cell_sf$intensity == "DC" &
                                cell_sf$cell_ID %in% chosen_cells, ] # to store error values
  cell_sf_elimcell$error <- rep(NA, nrow(cell_sf_elimcell))  # to store errors

  if (do_elimcell) {
    for (elim_cell in chosen_cells) {
      result <- test_elimcell(elim_cell, cell_df, cell_sf, model_type = "rf", f)
  
      # save
      prediction_error_results <- rbind(prediction_error_results,
  
                                  data.frame(model_type = c('rf'),
                                             elim_type = c('cell'),
                                             elim_year = c(NA),
                                             elim_cell = c(elim_cell),
                                             rmse = c(result$rmse_elimcell),
                                             error = c(result$error_elimcell),
                                             sampled_data = c(sample_data),
                                             fit_bias = c(NA)))
  
      # for mapping
      cell_sf_elimcell[cell_sf_elimcell$cell_ID == elim_cell, "error"] <- result$error_elimcell[1]
      }
  
    elimcell_error_map <- ggplot(cell_sf_elimcell) +
      geom_sf(aes(fill = error)) +
      scale_fill_viridis() +
      ggtitle(paste("Random forest prediction error, eliminated individual cell")) +
      geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", alpha = 0, linetype = 1) +
      theme_bw()
  
    print(elimcell_error_map)
  }
  
  
  # ols: regular validaton, 30% randomly eliminated  ----------------------------------------------
  
  ols_model1 <- lm(f, data = train)
  valid$ols_predicted_plant <- predict(ols_model1, valid)
  plot(valid$plant, valid$ols_predicted_plant, main = 'ols')
  abline(a = 0, b = 1)
  
  ols_rmse <- rmse(valid$plant, valid$ols_predicted_plant)
  ols_error <- mean(valid$ols_predicted_plant - valid$plant)
  
  
  # save
  prediction_error_results <- rbind(prediction_error_results,
                                    
                                data.frame(model_type = c('ols'),
                                           elim_type = c('30%'),
                                           elim_year = c(NA),
                                           elim_cell = c(NA),
                                           rmse = c(ols_rmse),
                                           error = c(ols_error),
                                           sampled_data = c(sample_data),
                                           fit_bias = c(NA)))
  
  
  # ols: fit on all data, then predict on training data -------------------------------------------
  # save residual and observed
  ols_model2 <- lm(f, data = cell_df)
  error_df <- data.frame(residual = ols_model2$residuals,
                         observed = cell_df$plant)
  
  # model residual vs observed, look at slope as measure of bias
  error_model <- lm(residual ~ observed, data = error_df)
  bias_measure <- error_model$coefficients['observed']
  
  plot(error_df$observed, error_df$residual, main = 'ols, trained on all data')
  plot(cell_df$onset, error_df$residual, main = 'ols, trained on all data')
  plot(cell_df$year, error_df$residual, main = 'ols, trained on all data')
  plot(cell_df$lat, error_df$residual, main = 'ols, trained on all data')
  plot(cell_df$lon, error_df$residual, main = 'ols, trained on all data')
  
   # save
  prediction_error_results <- rbind(prediction_error_results,
                                    
                                data.frame(model_type = c('ols'),
                                           elim_type = c('none'),
                                           elim_year = c(NA),
                                           elim_cell = c(NA),
                                           rmse = c(NA),
                                           error = c(NA),
                                           sampled_data = c(sample_data),
                                           fit_bias = c(bias_measure)))

  # ols: eliminate year -----------------------------------------------------------------------------
  
  if (do_elimyear) {
    for (elim_year in 2004:2014) {
      result <- test_elimyear(elim_year, cell_df, cell_sf, f, "ols")
      prediction_error_results <- rbind(prediction_error_results,
                                      
                                  data.frame(model_type = c('ols'),
                                             elim_type = c('year'),
                                             elim_year = c(elim_year),
                                             elim_cell = c(NA),
                                             rmse = c(result$rmse_elimyear),
                                             error = c(result$error_elimyear),
                                             sampled_data = c(sample_data),
                                             fit_bias = c(NA)))
       
      # print(result)
    }
  }

  
  # ols: eliminate cell -------------------------------------------------------------------------
  # chosen_cells was defined at rf's eliminate cell section
  cell_sf_elimcell <- cell_sf[cell_sf$year == 2004 & cell_sf$intensity == "DC" &
                                cell_sf$cell_ID %in% chosen_cells, ] # to store error values
  cell_sf_elimcell$error <- rep(NA, nrow(cell_sf_elimcell))  # to store errors

  if (do_elimcell) {
    for (elim_cell in chosen_cells) {
      result <- test_elimcell(elim_cell, cell_df, cell_sf, model_type = "ols", f)
  
      # save
      prediction_error_results <- rbind(prediction_error_results,
  
                                  data.frame(model_type = c('ols'),
                                             elim_type = c('cell'),
                                             elim_year = c(NA),
                                             elim_cell = c(elim_cell),
                                             rmse = c(result$rmse_elimcell),
                                             error = c(result$error_elimcell),
                                             sampled_data = c(sample_data),
                                             fit_bias = c(NA)))
  
      # print(result)
  
      # for mapping
      cell_sf_elimcell[cell_sf_elimcell$cell_ID == elim_cell, "error"] <- result$error_elimcell[1]
    }
  
    elimcell_error_map <- ggplot(cell_sf_elimcell) +
      geom_sf(aes(fill = error)) +
      scale_fill_viridis() +
      ggtitle(paste("OLS prediction error, eliminated individual cell")) +
      geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", alpha = 0, linetype = 1) +
      theme_bw()
  
    print(elimcell_error_map)
  }
}

print(prediction_error_results)

```

```{r}

elimyear_results <- prediction_error_results[prediction_error_results$elim_type == "year",]



ggplot(elimyear_results, aes(x = elim_year, y = rmse, col = model_type)) +
  geom_line() +
  ggtitle('eliminated year, rmse') + 
  theme_bw()

ggplot(elimyear_results, aes(x = elim_year, y = error, col = model_type)) +
  geom_line() +
  ggtitle('eliminated year, error') + 
  theme_bw()


elimcell_results <- prediction_error_results[prediction_error_results$elim_type == "cell",]

ggplot(elimcell_results, aes(x = elim_cell, y = rmse, col = model_type)) +
  geom_point() +
  ggtitle('eliminated cell, rmse') + 
  theme_bw()

ggplot(elimcell_results, aes(x = elim_cell, y = error, col = model_type)) +
  geom_point() +
  ggtitle('eliminated cell, error') + 
  theme_bw()

```