---
title: "Regular OLS"
output: html_document
---

1. Stepwise model selection, without spatial or temporal autocorrelation
2. Regular OLS for all years and for one year
3. Model evaluation (residual plots, residual autocorrelation)

## read data

```{r}

library(ggplot2)
library(tidyverse)
library(broom)
library(dplyr)
library(rgdal)
library(rgeos)
library(raster)
library(sf)
library(sp)
library(tmap)
library(viridis)
library(spdep)
library(spatialreg)
library(splm)
library(lmtest)

#E:/R-code/Modeling/code/FCN_clean_csvs.R
#~/Documents/R-code
source('E:/R-code/Modeling/code/FCN_clean_csvs.R')

MT_outline <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

median_cell_raw <- read.csv('E:/R-code/Modeling/data/median_onset_cell_v2.csv')
percentile5_cell_raw <- read.csv('E:/R-code/Modeling/data/percentile5_onset_cell_v2.csv')
percentile95_cell_raw <- read.csv('E:/R-code/Modeling/data/percentile95_onset_cell_v2.csv')

median_muni_raw <- read.csv('E:/R-code/Modeling/data/median_muni_v2.csv')
percentile5_muni_raw <- read.csv('E:/R-code/Modeling/data/percentile5_muni_v2.csv')
percentile95_muni_raw <- read.csv('E:/R-code/Modeling/data/percentile95_muni_v2.csv')

median_CARpoly_raw <- read.csv('E:/R-code/Modeling/data/median_CARpoly_v2.csv')
percentile5_CARpoly_raw <- read.csv('E:/R-code/Modeling/data/percentile5_CARpoly_v2.csv')
percentile95_CARpoly_raw <- read.csv('E:/R-code/Modeling/data/percentile95_CARpoly_v2.csv')

grid_1deg <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/grid_1deg', layer = 'grid_1deg')
munis <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/munis', layer = 'munis_SHP')
crs(munis) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")
  
MT_outline <- readOGR(dsn = 'E:/R-code/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

cell_sf <- st_read(dsn = 'E:/R-code/Modeling/data/shp/median_onset_cell', layer = 'median_onset_cell_SHP')

min_soy_area <- 2 #km2. min area of total or SC/DC soy in cell, muni or property to be considered in model


```

## functions

```{r}

# add cell_ID
clean_cell_ID <- function(cell_ID) {
  strsplit(cell_ID, "_")[[1]][2]
}




```

## read and clean spatial data

```{r}

# CSV DATA -----------------------------------------------------------------------------------------------------------------
# rename columns of CARpoly data and combine into a single csv before spatial join
median_CARpoly_raw <- rename_cols_median_CARpoly(median_CARpoly_raw)
percentile5_CARpoly_raw <- rename_cols_percentile5_CARpoly(percentile5_CARpoly_raw)
percentile95_CARpoly_raw <- rename_cols_percentile95_CARpoly(percentile95_CARpoly_raw)
CARpoly_raw <- create_CARpoly_raw(median_CARpoly_raw, percentile5_CARpoly_raw, percentile95_CARpoly_raw)
CARpoly_raw <- join_CARpoly_to_muni(CARpoly_raw)

# median cell
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                    rename_cols_median_cell()
percentile5_cell <- percentile5_cell_raw %>% filter(year > 0)
percentile95_cell <- percentile95_cell_raw %>% filter(year > 0)

# median muni
median_muni <- median_muni_raw %>% rename_cols_median_muni()
percentile5_muni <- percentile5_muni_raw %>% filter(year > 0)
percentile95_muni <- percentile95_muni_raw %>% filter(year > 0)

# create tidy datasets
cell_tidy <- tidy_combine_cell(median_cell, percentile5_cell, percentile95_cell)
muni_tidy <- tidy_combine_muni(median_muni, percentile5_muni, percentile95_muni)
CARpoly_tidy <- tidy_CARpoly(CARpoly_raw)

# categorize numeric variables
cell_tidy <- categorize_vars_cell_tidy(cell_tidy)
cell_untidy <- categorize_vars_cell_untidy(median_cell)

muni_tidy <- categorize_vars_muni_tidy(muni_tidy)
muni_untidy <- categorize_vars_muni_untidy(median_muni)

CARpoly_tidy <- categorize_vars_CARpoly_tidy(CARpoly_tidy) %>% delete_cols_CARpoly_tidy()
CARpoly_untidy <- categorize_vars_CARpoly_untidy(CARpoly_raw)

# change rename cols and delete unnecessary cols
CARpoly_untidy <- CARpoly_untidy %>% rename_cols_CARpoly_untidy() %>%
                                    delete_cols_CARpoly_untidy()
  
# categorize as new or old or neither in planted soy age (so far only have it for cell scale)
cell_tidy <- cell_tidy %>% cell_categorize_soy_age()
cell_untidy <- cell_untidy %>% cell_categorize_soy_age()

# add year_index and year_factor
cell_tidy$year_index <- cell_tidy$year - 2003
cell_untidy$year_index <- cell_untidy$year - 2003
muni_tidy$year_index <- muni_tidy$year - 2003
muni_untidy$year_index <- muni_untidy$year - 2003
CARpoly_tidy$year_index <- CARpoly_tidy$year - 2003
CARpoly_untidy$year_index <- CARpoly_untidy$year - 2003

cell_tidy$year_factor <- cell_tidy$year %>% as.factor()
cell_untidy$year_factor <- cell_untidy$year %>% as.factor()
muni_tidy$year_factor <- muni_tidy$year %>% as.factor()
muni_untidy$year_factor <- muni_untidy$year %>% as.factor()
CARpoly_tidy$year_factor <- CARpoly_tidy$year %>% as.factor()
CARpoly_untidy$year_factor <- CARpoly_untidy$year %>% as.factor()

# use muni_code as factor
cell_tidy$Muni_code_factor <- cell_tidy$Muni_code %>% as.factor()
cell_untidy$Muni_code_factor <- cell_untidy$Muni_code %>% as.factor()
CARpoly_tidy$Muni_code_factor <- CARpoly_tidy$Muni_code %>% as.factor()
CARpoly_untidy$Muni_code_factor <- CARpoly_untidy$Muni_code %>% as.factor()

# SF DATA ------------------------------------------------------------------------------------------------

cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)


cell_sf_tidy_plant <- cell_sf %>% tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_harvest, DC_harvest))

cell_sf_tidy_harvest <- cell_sf %>% tidy_by_intensity_harvest("SC_harvest", "DC_harvest") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_plant, DC_plant))

cell_sf_tidy_plant$year_index <- cell_sf_tidy_plant$year - 2003
cell_sf_tidy_harvest$year_index <- cell_sf_tidy_harvest$year - 2003
```



## make plots

```{r}

year_oi <- 2011

cell_sf_tidy_plant <- cell_sf_tidy_plant %>% drop_na()
cell_sf_tidy_harvest <- cell_sf_tidy_harvest %>% drop_na()

plot_cell_plant <- function(year, cell_data, intensity, limits_labels) {
  cell_year <- cell_data[cell_data$year == year, ]
  
  ggplot(cell_year) +
   geom_sf(aes(fill = plant_category), colour = NA) +
   #scale_fill_viridis(limits = c(50, 150)) +
   #scale_fill_continuous(low = '#f7fcb9', high = '#31a354', na.value = 'white', space = "Lab", limits = c(50, 150)) +
    scale_fill_brewer(type = 'seq', palette = 'YlGnBu', limits = limits_labels) +
   ggtitle(paste(intensity, "plant", year)) +
   geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", alpha = 0, linetype = 1) +
   theme_bw() +
    theme(#axis.title.y=element_blank(),
        #axis.text.y=element_blank(), axis.ticks.y=element_blank(), 
        #axis.title.x=element_blank(),
        #axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        text = element_text(size=15))

}


plot_cell_harvest <- function(year, cell_data, intensity, limits_labels) {
  cell_year <- cell_data[cell_data$year == year, ]
  
  ggplot(cell_year) +
   geom_sf(aes(fill = harvest_category), colour = NA) +
   #scale_fill_viridis(limits = c(150, 250)) +
   #scale_fill_continuous(low = '#fde0dd', high = '#c51b8a', na.value = 'white', space = "Lab", limits = c(150, 250)) +
    scale_fill_brewer(type = 'seq', palette = 'YlOrRd', limits = limits_labels) +
   ggtitle(paste(intensity, "harvest", year)) +
   geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", alpha = 0, linetype = 1) +
   theme_bw() +
    theme(#axis.title.y=element_blank(),
        #axis.text.y=element_blank(), axis.ticks.y=element_blank(), 
        #axis.title.x=element_blank(),
        #axis.text.x=element_blank(), axis.ticks.x=element_blank(), 
        text = element_text(size=15))

}

limits_labels_plant <- c('50 - 75', '75 - 90', '90 - 105', '105 - 120', '120 - 135', '135 - 150')
limits_labels_harvest <- c('150 - 175', '175 - 190', '190 - 205', '205 - 220', '220 - 235', '235 - 250')

cell_sf_tidy_plant$plant_category <- cut(cell_sf_tidy_plant$plant, 
                                         breaks = c(50, 75, 90, 105, 120, 135, 150),
                                         labels = c('50 - 75', '75 - 90', '90 - 105', 
                                                    '105 - 120', '120 - 135', '135 - 150'))
cell_sf_tidy_harvest$harvest_category <- cut(cell_sf_tidy_harvest$harvest, 
                                         breaks = c(150, 175, 190, 205, 220, 235, 250),
                                         labels = c('150 - 175', '175 - 190', '190 - 205', 
                                                    '205 - 220', '220 - 235', '235 - 250'))
# create categories for plotting
cell_sf_tidy_plant_DC <- cell_sf_tidy_plant[cell_sf_tidy_plant$intensity == "DC",] %>% 
                        filter(plant > 50)
cell_sf_tidy_harvest_DC <- cell_sf_tidy_harvest[cell_sf_tidy_harvest$intensity == "DC",] %>% 
                        filter(harvest < 250)
cell_sf_tidy_plant_SC <- cell_sf_tidy_plant[cell_sf_tidy_plant$intensity == "SC",] %>% 
                        filter(plant > 50)
cell_sf_tidy_harvest_SC <- cell_sf_tidy_harvest[cell_sf_tidy_harvest$intensity == "SC",] %>% 
                        filter(harvest < 250)


print(plot_cell_plant(year_oi, cell_sf_tidy_plant_DC, "DC", limits_labels_plant))
print(plot_cell_harvest(year_oi, cell_sf_tidy_harvest_DC, "DC", limits_labels_harvest))
print(plot_cell_plant(year_oi, cell_sf_tidy_plant_SC, "SC", limits_labels_plant))
print(plot_cell_harvest(year_oi, cell_sf_tidy_harvest_SC, "SC", limits_labels_harvest))
```
