---
title: "Explore_Compare_Onset"
output: html_document
---

## import data

```{r}

library(ggplot2)
library(tidyverse)
library(broom)
library(dplyr)
library(rgdal)
library(rgeos)
library(raster)
library(sf)
library(sp)
library(tmap)
library(viridis)
library(spdep)
library(Metrics) # for rmse
library(leaflet)

source('E:/R-code2/Modeling/code/FCN_clean_csvs.R')
source('E:/R-code2/Modeling/code/FCN_plotting.R')
source('E:/R-code2/Modeling/code/FCN_sample_data.R')

onset_type <- 'thres_10_persiann' #'AA_25_chirps_ATchirps5km' # 'Gabriel_onset'


if (onset_type != 'Gabriel_onset') {
  filename_median <- paste0('E:/R-code-large-files/data_onset_', onset_type, '/median_onset_cell_', onset_type, '.csv')
  filename_shp<- paste0('E:/R-code-large-files/data_onset_', onset_type, '/shp')
  layername_shp <- paste0('median_onset_cell_SHP_', onset_type)
  
  median_cell_raw <- read.csv(filename_median)
  
  cell_sf <- st_read(dsn = filename_shp, layer = layername_shp)
}

if (onset_type == 'Gabriel_onset') {
  median_cell_raw <- read.csv('E:/R-code2/Modeling/data/median_onset_cell_v2.csv')
  
  cell_sf <- st_read(dsn = 'E:/R-code2/Modeling/data/shp/median_onset_cell', layer = 'median_onset_cell_SHP')
}


MT_outline <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/MatoGrossoOutline', layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

grid_1deg <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/grid_1deg', layer = 'grid_1deg')
munis <- readOGR(dsn = 'E:/R-code2/Modeling/data/shp/munis', layer = 'munis_SHP')
crs(munis) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

# read in all the onsets. only the csv, not shp
all_onset_types <- c('Gabriel_onset', 'AA_2_persiann', 'AA_3_persiann', 
                      'AA_25_persiann', 'AA_25_chirps_ATgabriel25km', 'AA_25_persiann_ATgabriel25km',
                     'freq_5_persiann', 'freq_8_persiann', 'freq_10_persiann', 'freq_12_persiann',
                     'monsoon_30_persiann', 'monsoon_40_persiann',
                     'pentad_8_persiann', 'pentad_10_persiann', 'pentad_15_persiann',
                     'rangethres_10_15_15_30_persiann', 'rangethres_10_15_15_40_persiann',
                     'rangethres_10_15_20_20_persiann', 'rangethres_10_15_20_30_persiann',
                     'rangethres_10_15_30_40_persiann', 'thres_10_persiann')
# didn't do:  'AA_25_chirps_ATchirps5km'
```

## data cleaning

```{r}

# CSV DATA ------------------------------------------------------------------------------
# median cell for onset of interest
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                    rename_cols_median_cell()
median_cell$plant_stat_type <- rep('median', nrow(median_cell))


# add onset data from different onset definitions
all_onset_data <- data.frame(onset = numeric(0),
                             lat = numeric(0),
                             lon = numeric(0),
                             year = numeric(0),
                             onset_type = character(0))

for (onset_name in all_onset_types) {
  if (onset_name != 'Gabriel_onset') {
    filename_median <- paste0('E:/R-code-large-files/data_onset_', onset_name, 
                              '/median_onset_cell_', onset_name, '.csv')
    data <- read.csv(filename_median)
  }
  
  if (onset_name == 'Gabriel_onset') {
    data <- median_cell_raw <- read.csv('E:/R-code2/Modeling/data/median_onset_cell_v2.csv')
  }
  
  onset_data <- data[,c('onset_median', 'latitude_median', 'longitude_median', 'year_median')]
  onset_data$onset_type <- onset_name
  names(onset_data) <- c('onset', 'lat', 'lon', 'year', 'onset_type')

  all_onset_data <- rbind(all_onset_data, onset_data)
}

all_onset_data$year_factor <- as.factor(all_onset_data$year)

# SF DATA -------------------------------------------------------------------------------

# get cell_ID column for median
cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)

# join median, percentile data to cell_sf
# cell_sf has median information, but copy it and put in percentile info for DC and SC plant

cell_sf$plant_stat_type <- rep("median", nrow(cell_sf))

cell_sf_tidy <- cell_sf %>% #tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            #tidy_by_intensity_delay("SC_delay", "DC_delay") %>%
            dplyr::select(-c(SC_harvest, DC_harvest, SC_plant, DC_plant)) #%>%
            #categorize_regions_cell_sf_tidy() # categorize cells into four regions

cell_sf_tidy$year_index <- cell_sf_tidy$year - 2003
cell_sf_tidy$year_factor <- as.factor(cell_sf_tidy$year)

cell_sf_tidy <- cell_sf_tidy %>%  drop_na


# calculate quantiles of onset
onset_oi_data <- cell_sf_tidy %>% 
                    mutate(onset_quantile_allyears = ntile(onset, 10))
```

## Spatial vs temporal variability of individual onset (the onset_oi)

```{r}

# boxplot
ggplot(onset_oi_data) +
  geom_boxplot(aes(x=year_factor, y=onset)) +
  ggtitle(onset_type) +
  ylim(0, 130) +
  theme_bw()

# map which cells belong to which quantile

quantile_maps <- ggplot(onset_oi_data) +
      geom_sf(aes(fill = onset_quantile_allyears), color = NA) +
      #scale_fill_viridis() +
      scale_fill_gradient(low="black", high="red") +
      #scale_fill_brewer(palette="YlOrRd") +
      ggtitle(paste("Onset quantile for all years, pooled,", onset_type)) +
      geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", 
                   alpha = 0, linetype = 1) +
      facet_wrap(~year_factor) +
      theme_bw()

print(quantile_maps)
```

## Spatial patterns' persistence over time

```{r}

onset_oi_data <- onset_oi_data %>% group_by(year_factor) %>%
  mutate(onset_quantile_eachyear = ntile(onset, 10))

quantile_maps <- ggplot(onset_oi_data) +
      geom_sf(aes(fill = onset_quantile_eachyear), color = NA) +
      #scale_fill_viridis() +
      scale_fill_gradient(low="black", high="blue") +
      #scale_fill_brewer(palette="YlOrRd") +
      ggtitle(paste("Onset quantile for individual years,", onset_type)) +
      geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", 
                   alpha = 0, linetype = 1) +
      facet_wrap(~year_factor) +
      theme_bw()

print(quantile_maps)

onset_oi_data <- onset_oi_data %>% ungroup()

# calculate time-averaged quantiles
# get cells from 2004, filter out all other cells from the other years
cellID_2004 <- onset_oi_data[onset_oi_data$year == 2004, "cell_ID"]
st_geometry(cellID_2004) <- NULL
onset_oi_data_subset <- onset_oi_data[onset_oi_data$cell_ID %in% cellID_2004$cell_ID,]

# group by cell_ID and calculate mean onset
onset_oi_summarized <- onset_oi_data_subset %>% group_by(cell_ID) %>%
                                             summarize(onset_quantile_median = median(onset_quantile_eachyear),
                                                   onset_quantile_mean = mean(onset_quantile_eachyear)) %>%
                                             ungroup()

quantile_map_summary <- ggplot(onset_oi_summarized) +
      geom_sf(aes(fill = onset_quantile_median), color = NA) +
      #scale_fill_viridis() +
      scale_fill_gradient(low="black", high="blue") +
      #scale_fill_brewer(palette="YlOrRd") +
      ggtitle(paste("Median onset quantile, all years,", onset_type)) +
      geom_polygon(data = MT_outline, aes(x = long, y = lat), color = "black", 
                   alpha = 0, linetype = 1) +
      theme_bw()

print(quantile_map_summary)
```

## Temporal patterns across onset definitions

```{r}

onset_types_toplot <-  c('Gabriel_onset', 'thres_10_persiann')

# c('Gabriel_onset', 'AA_2_persiann', 'AA_25_persiann', 'AA_3_persiann')
# c('Gabriel_onset', 'freq_5_persiann', 'freq_8_persiann', 'freq_10_persiann', 'freq_12_persiann')
# c('Gabriel_onset', 'monsoon_30_persiann', 'monsoon_40_persiann')
# c('Gabriel_onset', 'pentad_8_persiann', 'pentad_10_persiann', 'pentad_15_persiann')
# c('Gabriel_onset', 'rangethres_10_15_15_30_persiann', 'rangethres_10_15_15_40_persiann', 'rangethres_10_15_20_20_persiann', 'rangethres_10_15_20_30_persiann', 'rangethres_10_15_30_40_persiann')
# c('Gabriel_onset', 'thres_10_persiann')

onset_data_toplot <- all_onset_data[all_onset_data$onset_type %in% onset_types_toplot,]

# boxplot
ggplot(onset_data_toplot) +
  geom_boxplot(aes(x=year_factor, y=onset, col = onset_type)) +
  scale_color_brewer(palette="Blues") +
  #scale_fill_viridis() +
  ggtitle('Temporal patterns across all onset') +
  labs(x = 'year') +
  ylim(0, 130) +
  theme_bw()

# group by year and onset_type, then calc median and stdev
onset_data_summarized_eachyear <- onset_data_toplot %>% group_by(year_factor, onset_type) %>%
                                             summarize(onset_median = median(onset),
                                                   onset_stdev = sd(onset)) %>%
                                             ungroup()
onset_data_summarized_pooledyear <- onset_data_toplot %>% group_by(onset_type) %>%
                                             summarize(onset_median = median(onset),
                                                   onset_stdev = sd(onset)) %>%
                                             ungroup()
onset_data_summarized_pooledyear$year_factor <- "all"

onset_data_summarized <- rbind(onset_data_summarized_eachyear, onset_data_summarized_pooledyear)

# timeseries plot
# ggplot(onset_data_summarized, aes(x = year_factor)) +
#   geom_point(aes(y = onset_median, col = onset_type), position = position_dodge(0.5)) +
#   geom_errorbar(aes(ymin = onset_median-onset_stdev, ymax = onset_median+onset_stdev, 
#                     col = onset_type), position = position_dodge(0.5)) +
#   scale_color_brewer(palette="Blues") +
#   #scale_fill_viridis() +
#   ggtitle('Temporal patterns across onset definitions') +
#   labs(x = 'year') +
#   ylim(20, 100) +
#   theme_bw()

ggplot(onset_data_summarized, aes(x = onset_type)) +
  geom_point(aes(y = onset_median, col = onset_type), position = position_dodge(0.5)) +
  geom_errorbar(aes(ymin = onset_median-onset_stdev, ymax = onset_median+onset_stdev, 
                    col = onset_type), position = position_dodge(0.5)) +
  scale_color_brewer(palette="Blues") +
  ggtitle('Temporal patterns across onset definitions') +
  facet_wrap(~year_factor) +
  ylim(20, 100) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1, vjust = 0.5)) 
  #scale_x_discrete(labels = abbreviate)

# plot stdev of onsets
ggplot(onset_data_summarized) +
  geom_bar(aes(x = year_factor, y = onset_stdev, fill = onset_type), position=position_dodge(), stat = 'identity') +
  scale_fill_brewer(palette="Blues") +
  #scale_fill_viridis() +
  ggtitle('Stdev of onset within each year') +
  labs(x = 'year') +
  theme_bw()
```