---
title: "Crop Timing Histogram"
output: html_document
---

## Input is from GEE Visualization/Export_Histograms

The histograms are for first (soy) crop aggregated over 5km scale over MT
Note, the crop timing is exported with plant and harvest separately, but manually put them in the same file

```{r setup}
library(ggplot2)
library(ggridges)
library(viridis)
library(RColorBrewer)

onset_data <- read.csv('input/onset_median_MT.csv') # onset_median_MT.csv
timing_doubleFirst <- read.csv('input/histogram_doubleFirst_MT.csv') # histogram_doubleFirst_MT.csv
timing_single <- read.csv('input/histogram_single_MT.csv') # histogram_single_MT.csv
onset_hist <- read.csv('input/histogram_onset_MT.csv')
onset_plant_doubleFirst <- read.csv('input/onset_plant_doubleFirst_MT.csv')
onset_plant_single <- read.csv('input/onset_plant_single_MT.csv')
cycle_doubleFirst <- read.csv('input/crop_cycle_doubleFirst_MT.csv')
cycle_single <- read.csv('input/crop_cycle_single_MT.csv')
median_plant_single <- read.csv('input/median_plant_single_MT.csv')
median_plant_doubleFirst <- read.csv('input/median_plant_doubleFirst_MT.csv')
median_harvest_single <- read.csv('input/median_harvest_single_MT.csv')
median_harvest_doubleFirst <- read.csv('input/median_harvest_doubleFirst_MT.csv')
median_delay_single <- read.csv('input/median_delay_single_MT.csv')
median_delay_doubleFirst <- read.csv('input/median_delay_doubleFirst_MT.csv')
```

## Double crop

```{r doubleCrop}
# DOUBLE PLANT AND HARVEST

ggplot(timing_doubleFirst, aes(x = timing_doubleFirst$DOY, y = timing_doubleFirst$Year, height = timing_doubleFirst$Count, group = timing_doubleFirst$Year, fill = timing_doubleFirst$DOY)) + 
  xlim(0, 250) +
  xlab("DOY from Aug 1") +
  ylab("Year") +
  ggtitle("Double cropped soy") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days after Aug 1') +
  geom_segment(data = onset_data, aes(x = median_onset, y = year, group = year, xend = median_onset, yend = year + 0.9, height = rep(100, 11), fill = median_onset), color = "red", size = 1) +
  geom_segment(data = median_plant_doubleFirst, aes(x = median_plant, y = year, group = year, xend = median_plant, yend = year + 0.9, height = rep(100, 11), fill = median_plant), color = "black", size = 1) +
  geom_segment(data = median_harvest_doubleFirst, aes(x = median_harvest, y = year, group = year, xend = median_harvest, yend = year + 0.9, height = rep(100, 11), fill = median_harvest), color = "black", size = 1) +
  theme_bw()

# Onset minus plant
ggplot(onset_plant_doubleFirst, aes(x = onset_plant_doubleFirst$DOY, y = onset_plant_doubleFirst$Year, height = onset_plant_doubleFirst$Count, group = onset_plant_doubleFirst$Year, fill = onset_plant_doubleFirst$DOY)) + 
  xlim(-20, 80) +
  xlab("Days") +
  ylab("Year") +
  ggtitle("Planting date minus onset, double cropped soy") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days', option = "C", direction = -1) +
  geom_segment(data = onset_data, aes(x = 0, y = year, group = year, xend = 0, yend = year + 1.5, height = rep(100, 11), fill = median_onset), color = "blue", size = 1) +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()

# crop cycle
ggplot(cycle_doubleFirst, aes(x = cycle_doubleFirst$DOY, y = cycle_doubleFirst$Year, height = cycle_doubleFirst$Count, group = cycle_doubleFirst$Year, fill = cycle_doubleFirst$DOY)) + 
  xlim(70, 150) +
  xlab("Days") +
  ylab("Year") +
  ggtitle("Crop Cycle Length, double crop") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days') +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()
```

## Single Crop

```{r singleCrop}
# SINGLE PLANT AND HARVEST

ggplot(timing_single, aes(x = timing_single$DOY, y = timing_single$Year, height = timing_single$Count, group = timing_single$Year, fill = timing_single$DOY)) + 
  xlim(0, 250) +
  xlab("DOY from Aug 1") +
  ylab("Year") +
  ggtitle("Single cropped soy") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days after Aug 1') +
  geom_segment(data = onset_data, aes(x = median_onset, y = year, group = year, xend = median_onset, yend = year + 0.9, height = rep(100, 11), fill = median_onset), color = "red", size = 1) +
    geom_segment(data = median_plant_single, aes(x = median_plant, y = year, group = year, xend = median_plant, yend = year + 0.9, height = rep(100, 11), fill = median_plant), color = "black", size = 1) +
    geom_segment(data = median_harvest_single, aes(x = median_harvest, y = year, group = year, xend = median_harvest, yend = year + 0.9, height = rep(100, 11), fill = median_harvest), color = "black", size = 1) +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()

# Onset minus plant
ggplot(onset_plant_single, aes(x = onset_plant_single$DOY, y = onset_plant_single$Year, height = onset_plant_single$Count, group = onset_plant_single$Year, fill = onset_plant_single$DOY)) + 
  xlim(-20, 80) +
  xlab("Days") +
  ylab("Year") +
  ggtitle("Planting date minus onset, single cropped soy") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days', option = "C", direction = -1) +
  geom_segment(data = onset_data, aes(x = 0, y = year, group = year, xend = 0, yend = year + 1.5, height = rep(100, 11), fill = median_onset), color = "blue", size = 1) +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()

# crop cycle
ggplot(cycle_single, aes(x = cycle_single$DOY, y = cycle_single$Year, height = cycle_single$Count, group = cycle_single$Year, fill = cycle_single$DOY)) + 
  xlim(70, 150) +
  xlab("Days") +
  ylab("Year") +
  ggtitle("Crop Cycle Length, single crop") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days') +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()
```

## Onset

```{r onset}
# wet season onset

ggplot(onset_hist, aes(x = onset_hist$DOY, y = onset_hist$Year, height = onset_hist$Count, group = onset_hist$Year, fill = onset_hist$DOY)) + 
  xlim(0, 250) +
  xlab("DOY from Aug 1") +
  ylab("Year") +
  ggtitle("Onset") +
  geom_density_ridges_gradient(stat = "identity", scale = 1) +
  scale_fill_viridis(name = 'Days after Aug 1') +
  scale_y_continuous(breaks=seq(2004, 2014, 1)) +
  theme_bw()

```
