---
title: "Predictions"
output: html_document
---

Import and clean data

```{r}

# import data

library(ggplot2)
library(tidyverse)
library(dplyr)
library(rgdal)
library(raster)
library(sf)
library(sp)
library(leaps)
library(viridis)
library(spatial)
library(spdep)
library(plm)
library(stringr)
library(fmsb) # calculate percentile

os_system <- 'windows' # mac for laptop or windows for desktop
if (os_system == 'windows') {first_folder <- 'E:'}
if (os_system == 'mac') {first_folder <- '~/Documents'}
if (os_system == 'windows_laptop') {first_folder <- 'D:'}

#E:/R-code/Modeling/code/FCN_clean_csvs.R
#~/Documents/R-code
source(paste0(first_folder,'/R-code2/Modeling/code/FCN_clean_csvs.R'))
source(paste0(first_folder,'/R-code2/Modeling/code/FCN_plotting.R'))
source(paste0(first_folder,'/R-code2/Modeling/code/FCN_sample_data.R'))
source(paste0(first_folder,'/R-code2/Modeling/code/FCN_run_model_spatial_sampled.R'))


MT_outline <- readOGR(dsn = paste0(first_folder,'/R-code2/Modeling/data/shp/MatoGrossoOutline'), layer = 'MatoGrossoOutline')
crs(MT_outline) <- CRS("+proj=longlat +datum=WGS84 +no_defs +ellps=WGS84 +towgs84=0,0,0")

```

# Note: we use demise_AA_25_persiann because we use AA_2.5_persiann to make predictions

```{r}
onset_oi <- 'demise_AA_25_persiann' #'freq_8_chirps_ATchirps5km' #'freq_10_persiann'

# FOR onset_oi ------------------------------------------------------------------------------------------------------------------------
# read and clean the data ---------------------------------------------------------------------------------------------------------
filename_median <- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi, '/median_onset_cell_onset_', onset_oi , '.csv')
filename_percentile5 <- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi , '/percentile5_onset_cell_onset_', onset_oi , '.csv')
filename_percentile25 <- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi , '/percentile25_onset_cell_onset_', onset_oi , '.csv')
filename_percentile75 <- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi, 
                                  '/percentile75_onset_cell_onset_', onset_oi, '.csv')
filename_percentile95 <- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi, 
                                  '/percentile95_onset_cell_onset_', onset_oi, '.csv')

filename_shp<- paste0(first_folder,'/R-code-large-files/data_onset_', onset_oi , '/shp')
layername_shp <- paste0('median_onset_cell_SHP_onset_', onset_oi )
    
median_cell_raw <- read.csv(filename_median)
percentile5_cell_raw <- read.csv(filename_percentile5)
percentile25_cell_raw <- read.csv(filename_percentile25)
percentile75_cell_raw <- read.csv(filename_percentile75)
percentile95_cell_raw <- read.csv(filename_percentile95)

cell_sf <- st_read(dsn = filename_shp, layer = layername_shp)
 
# CSV DATA -----------------------------------------------------------------------------------------------
# median cell
median_cell <- median_cell_raw %>% delete_cols_median_cell() %>%
                                      rename_cols_median_cell()
median_cell$plant_stat_type <- rep('median', nrow(median_cell))
median_cell <- median_cell %>% rename(demise = demise_median) %>% dplyr::select(-demise_sum)
  
# percentiles
percentile5_cell <- percentile5_cell_raw %>% rename_cols_percentile_cell() 
percentile25_cell <- percentile25_cell_raw %>% rename_cols_percentile_cell() 
percentile75_cell <- percentile75_cell_raw %>% rename_cols_percentile_cell() 
percentile95_cell <- percentile95_cell_raw %>% rename_cols_percentile_cell()
  
# SF DATA ------------------------------------------------------------------------------------------------
  
# get cell_ID column for median
cell_sf$cell_ID <- median_cell$cell_ID
cell_sf$cell_ID <- sapply(as.character(cell_sf$cell_ID), clean_cell_ID)
  
# join median, percentile data to cell_sf
# cell_sf has median information, but copy it and put in percentile info for DC and SC plant
  
cell_sf$plant_stat_type <- rep("median", nrow(cell_sf))
cell_sf$demise <- median_cell$demise
  
cell_sf_percentile5 <- cell_sf
cell_sf_percentile5$SC_plant <- percentile5_cell$SC_plant
cell_sf_percentile5$DC_plant <- percentile5_cell$DC_plant
cell_sf_percentile5$plant_stat_type <- rep("percentile5", nrow(cell_sf_percentile5))
  
cell_sf_percentile25 <- cell_sf
cell_sf_percentile25$SC_plant <- percentile25_cell$SC_plant
cell_sf_percentile25$DC_plant <- percentile25_cell$DC_plant
cell_sf_percentile25$plant_stat_type <- rep("percentile25", nrow(cell_sf_percentile25))

cell_sf_percentile75 <- cell_sf
cell_sf_percentile75$SC_plant <- percentile75_cell$SC_plant
cell_sf_percentile75$DC_plant <- percentile75_cell$DC_plant
cell_sf_percentile75$plant_stat_type <- rep("percentile75", nrow(cell_sf_percentile75))

cell_sf_percentile95 <- cell_sf
cell_sf_percentile95$SC_plant <- percentile95_cell$SC_plant
cell_sf_percentile95$DC_plant <- percentile95_cell$DC_plant
cell_sf_percentile95$plant_stat_type <- rep("percentile95", nrow(cell_sf_percentile95))

cell_sf <- rbind(cell_sf, cell_sf_percentile5, cell_sf_percentile25, cell_sf_percentile75, cell_sf_percentile95)
  
cell_sf_tidy <- cell_sf %>% tidy_by_intensity_plant("SC_plant", "DC_plant") %>%
            dplyr::select(-c(SC_harvest, DC_harvest)) %>%
            categorize_regions_cell_sf_tidy() # categorize cells into four regions
  
cell_sf_tidy$year_index <- cell_sf_tidy$year - 2003
cell_sf_tidy$year_factor <- as.factor(cell_sf_tidy$year)
  
cell_sf_tidy <- cell_sf_tidy %>%  drop_na
cell_sf_tidy$delay <- cell_sf_tidy$plant - cell_sf_tidy$onset

# change 'median' to 'percentile50'
cell_df <- cell_sf_tidy
st_geometry(cell_df) <- NULL
cell_df[which(cell_df[,"plant_stat_type"] == "median"), "plant_stat_type"] <- "percentile50"

cell_sf_tidy$percentile <- cell_df$plant_stat_type
```

## plot of onset, demise predictions

```{r}

library(tidyr)
nw_predictions <- read.csv(paste0(first_folder,'/R-code2/ModelingPaper/northwest_MT_prediction_csv.csv'))
ne_predictions <- read.csv(paste0(first_folder,'/R-code2/ModelingPaper/northeast_MT_prediction_csv.csv'))

# CHANGE ONSET AND DEMISE from days after July 1 (the input) to days after Aug 1
nw_predictions$outoday <- nw_predictions$outoday - 31
nw_predictions$outeday <- nw_predictions$outeday - 31
ne_predictions$outoday <- ne_predictions$outoday - 31
ne_predictions$outeday <- ne_predictions$outeday - 31

nw_predictions_tidy <- nw_predictions %>% 
  rename(onset = outoday, demise = outeday) %>%
  gather("wet_season_metric", "day", 2:3)

ne_predictions_tidy <- ne_predictions %>% 
  rename(onset = outoday, demise = outeday) %>%
  gather("wet_season_metric", "day", 2:3)

nw_predictions <- nw_predictions %>% 
  rename(onset = outoday, demise = outeday, length = outslen)

ne_predictions <- ne_predictions %>% 
  rename(onset = outoday, demise = outeday, length = outslen)

nw_onset_mean_before <- mean(nw_predictions[nw_predictions$time <= 2000, 'onset'])
nw_onset_mean_after <- mean(nw_predictions[nw_predictions$time >= 2020, 'onset'])
nw_demise_mean_before <- mean(nw_predictions[nw_predictions$time <= 2000, 'demise'])
nw_demise_mean_after <- mean(nw_predictions[nw_predictions$time >= 2020, 'demise'])
nw_length_mean_before <- mean(nw_predictions[nw_predictions$time <= 2000, 'length'])
nw_length_mean_after <- mean(nw_predictions[nw_predictions$time >= 2020, 'length'])

ne_onset_mean_before <- mean(ne_predictions[ne_predictions$time <= 2000, 'onset'])
ne_onset_mean_after <- mean(ne_predictions[ne_predictions$time >= 2020, 'onset'])
ne_demise_mean_before <- mean(ne_predictions[ne_predictions$time <= 2000, 'demise'])
ne_demise_mean_after <- mean(ne_predictions[ne_predictions$time >= 2020, 'demise'])
ne_length_mean_before <- mean(ne_predictions[ne_predictions$time <= 2000, 'length'])
ne_length_mean_after <- mean(ne_predictions[ne_predictions$time >= 2020, 'length'])

# plot onset and demise
ggplot(nw_predictions_tidy) +
  geom_rect(mapping=aes(xmin=2000, xmax=2020, ymin=50, ymax=400), fill="lightgray", alpha=0.1) +
  geom_line(aes(x = time, y = day, color = wet_season_metric)) +
  geom_segment(aes(x = 1970, y = nw_onset_mean_before, xend = 2000, yend = nw_onset_mean_before), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 1970, y = nw_demise_mean_before, xend = 2000, yend = nw_demise_mean_before), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = nw_onset_mean_after, xend = 2049, yend = nw_onset_mean_after), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = nw_demise_mean_after, xend = 2049, yend = nw_demise_mean_after), 
               col = 'black', size = 1, linetype = 'dashed') +
  ggtitle('Predictions for northwest Mato Grosso') +
  ylab('Days after Aug 1') +
  xlab('Year') +
  geom_text(aes(x = 1985, y = 375, label = "Historical"), color = "black", size = 5) +
  geom_text(aes(x = 2035, y = 375, label = "Predictions"), color = "black", size = 5) +
  theme_bw()

ggplot(ne_predictions_tidy) +
  geom_rect(mapping=aes(xmin=2000, xmax=2020, ymin=50, ymax=400), fill="lightgray", alpha=0.1) +
  geom_line(aes(x = time, y = day, color = wet_season_metric)) +
  geom_segment(aes(x = 1970, y = ne_onset_mean_before, xend = 2000, yend = ne_onset_mean_before), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 1970, y = ne_demise_mean_before, xend = 2000, yend = ne_demise_mean_before), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = ne_onset_mean_after, xend = 2049, yend = ne_onset_mean_after), 
               col = 'black', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = ne_demise_mean_after, xend = 2049, yend = ne_demise_mean_after), 
               col = 'black', size = 1, linetype = 'dashed') +
  ggtitle('Predictions for northeast Mato Grosso') +
  ylab('Days after Aug 1') +
  xlab('Year') +
  geom_text(aes(x = 1985, y = 375, label = "Historical"), color = "black", size = 5) +
  geom_text(aes(x = 2035, y = 375, label = "Predictions"), color = "black", size = 5) +
  theme_bw()

# plot wet season length
ggplot(nw_predictions) +
  geom_rect(mapping=aes(xmin=2000, xmax=2020, ymin=150, ymax=320), fill="lightgray", alpha=0.1) +
  geom_line(aes(x = time, y = length)) +
  geom_segment(aes(x = 1970, y = nw_length_mean_before, xend = 2000, yend = nw_length_mean_before), 
               col = 'blue', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = nw_length_mean_after, xend = 2049, yend = nw_length_mean_after), 
               col = 'blue', size = 1, linetype = 'dashed') +
  geom_hline(yintercept = 200, color = 'red') +
  ggtitle('Predictions for northwest Mato Grosso') +
  ylab('Wet season length') +
  xlab('Year') +
  geom_text(aes(x = 1985, y = 300, label = "Historical"), color = "black", size = 5) +
  geom_text(aes(x = 2035, y = 300, label = "Predictions"), color = "black", size = 5) +
  theme_bw()

ggplot(ne_predictions) +
  geom_rect(mapping=aes(xmin=2000, xmax=2020, ymin=150, ymax=320), fill="lightgray", alpha=0.1) +
  geom_line(aes(x = time, y = length)) +
  geom_segment(aes(x = 1970, y = ne_length_mean_before, xend = 2000, yend = ne_length_mean_before), 
               col = 'blue', size = 1, linetype = 'dashed') +
  geom_segment(aes(x = 2020, y = ne_length_mean_after, xend = 2049, yend = ne_length_mean_after), 
               col = 'blue', size = 1, linetype = 'dashed') +
  geom_hline(yintercept = 200, color = 'red') +
  ggtitle('Predictions for northeast Mato Grosso') +
  ylab('Wet season length') +
  xlab('Year') +
  geom_text(aes(x = 1985, y = 300, label = "Historical"), color = "black", size = 5) +
  geom_text(aes(x = 2035, y = 300, label = "Predictions"), color = "black", size = 5) +
  theme_bw()

ggplot(ne_predictions_tidy) +
  geom_line(aes(x = time, y = day, color = wet_season_metric), size = 2) +
  ggtitle('Predictions for northeast Mato Grosso') +
  ylab('Days after Aug 1') +
  xlab('Year') +
  xlim(c(2020, 2050)) +
  coord_fixed(ratio = 0.04) +
  theme_bw()

ggplot(nw_predictions_tidy) +
  geom_line(aes(x = time, y = day, color = wet_season_metric), size = 2) +
  ggtitle('Predictions for northwest Mato Grosso') +
  ylab('Days after Aug 1') +
  xlab('Year') +
  xlim(c(2020, 2050)) +
  coord_fixed(ratio = 0.04) +
  theme_bw()

# calculate change in onset in 2020- 2049 relative to 1970 - 2000 for likelihood calculations
delta_onset_ne_predictions <- ne_predictions
delta_onset_ne_predictions$delta_onset <- delta_onset_ne_predictions$onset - ne_onset_mean_before
delta_onset_ne_predictions$region <- 'vulnerable'
delta_onset_ne_predictions <- delta_onset_ne_predictions %>% dplyr::filter(time >= 2020) 
# calculate percentile of delta_onset after filtering only the future years
delta_onset_ne_predictions$delta_onset_percentile <- percentile(delta_onset_ne_predictions$delta_onset)
delta_onset_ne_predictions <- delta_onset_ne_predictions %>%
  dplyr::select(c('time', 'delta_onset', 'delta_onset_percentile', 'onset', 'demise', 'length', 'region')) %>%
  dplyr::rename(year = time)

delta_onset_nw_predictions <- nw_predictions
delta_onset_nw_predictions$delta_onset <- delta_onset_nw_predictions$onset - nw_onset_mean_before
delta_onset_nw_predictions$region <- 'not_vulnerable'
delta_onset_nw_predictions <- delta_onset_nw_predictions %>% dplyr::filter(time >= 2020) 
# calculate percentile of delta_onset after filtering only the future years
delta_onset_nw_predictions$delta_onset_percentile <- percentile(delta_onset_nw_predictions$delta_onset)
delta_onset_nw_predictions <- delta_onset_nw_predictions %>%
  dplyr::select(c('time', 'delta_onset', 'delta_onset_percentile', 'onset', 'demise', 'length', 'region')) %>%
  dplyr::rename(year = time)

delta_onset_predictions <- rbind(delta_onset_ne_predictions, delta_onset_nw_predictions)
```


Given a year and region, plot planting date CDF and make predictions from it

```{r}

year_oi <- 2014 # AVOID USING THIS FOR 2004 - 2014 AVERAGE

# onset regions and change

case_name <- 'lateOn_earlyDem' # lateOn_earlyDem, medOn_medDem, earlyOn_lateDem

# WORST CASE

if (case_name == 'lateOn_earlyDem') {
  onset_change_vulnerable <- 20.92
  onset_change_not_vulnerable <- 13.64
  demise_change_vulnerable <- -26.42
  demise_change_not_vulnerable <- -22.83
}

if (case_name == 'medOn_medDem') {
  onset_change_vulnerable <- 6.99 # CHANGE THIS
  onset_change_not_vulnerable <- 3.91 # CHANGE THIS
  demise_change_vulnerable <- -7.7 # CHANGE THIS
  demise_change_not_vulnerable <- -3.69 # CHANGE THIS
}

if (case_name == 'earlyOn_lateDem') {
  onset_change_vulnerable <- -9.16
  onset_change_not_vulnerable <- -4.48
  demise_change_vulnerable <- 4.06
  demise_change_not_vulnerable <- 9.93
}

region_cutoff <- -54 # longitude; to the west, 'not_vulnerable' and to the east, 'vulnerable'

SC_cycle_length <- 90
DC_cycle_length <- 200
year_change <- 10 # number of years after year_oi for prediction

cell_df <- cell_sf_tidy
st_geometry(cell_df) <- NULL

if (onset_oi == 'demise_AA_25_persiann') {
  coefs_onset_oi <- readRDS("FE_bootstrapped_coefs_AA_25_persiann.rds")
}

if (onset_oi == 'freq_10_persiann') {
  coefs_onset_oi <- readRDS("FE_bootstrapped_coefs_freq_10_persiann.rds")
}

if (onset_oi == 'freq_8_chirps_ATchirps5km') {
  coefs_onset_oi <- readRDS("FE_bootstrapped_coefs_freq_8_chirps_ATchirps5km.rds")
}

coefs_onset_oi$percentile <- as.character(coefs_onset_oi$percentile)
coefs_onset_oi[which(coefs_onset_oi[,"percentile"] == "median"), "percentile"] <- "percentile50"

# to store mean 'change in planting date' per 25km cell. 
predictions_summary <- data.frame(intensity = character(0),
                                  region = character(0),
                                  pred_type = character(0),
                                  # the average number of days planting is delayed in a 25km cell. 
                                  # NOTE: THESE PREDICTIONS for change_plant ARE ASSUMING THERE'S NO IMPACT OF ONSET TIMING ON PLANTING DATE
                                  change_plant = numeric(0), 
                                  # the percent of the 25km cell that is affected by late onset (i.e. can't plant as early as they otherwise would)
                                  percent_affected_late_onset = numeric(0),
                                  # percent of people who won't be able to do DC (or SC) due to earlier demise
                                  percent_affected_early_demise = numeric(0),
                                  # available days to plant the given intensity
                                  window = numeric(0),
                                  # the change in onset, compared to 2014, that must happen to have onset touch the 5th percentile of predicted plant
                                  delta_onset_touching5thpercentile = numeric(0),
                                  # ... and the likelihood of this change in onset (or worse) happening
                                  delta_onset_likelihood_touching5thpercentile = numeric(0),
                                  # the change in onset, compared to 2014, that must happen to have onset touch the 50th percentile of predicted plant
                                  delta_onset_touching50thpercentile = numeric(0),
                                  # ... and the likelihood of this change in onset (or worse) happening
                                  delta_onset_likelihood_touching50thpercentile = numeric(0))

for (intensity in c('SC', 'DC')) {
  for (region in c('vulnerable', 'not_vulnerable')) {
    
    # to store observations and predictions in CDF form
    predictions <- data.frame(percentile = numeric(0),
                              plant = numeric(0),
                              type = character(0))
    
    if (region == 'vulnerable') {
      cell_df_subset <- cell_df[cell_df$year == year_oi & cell_df$intensity == intensity & cell_df$lon > region_cutoff,] # east # cell_df$year == year_oi & 
      onset_change <- onset_change_vulnerable
      demise_change <- demise_change_vulnerable
    }
    if (region != 'vulnerable') {
      cell_df_subset <- cell_df[cell_df$year == year_oi & cell_df$intensity == intensity & cell_df$lon <= region_cutoff,] # west # cell_df$year == year_oi & 
      onset_change <- onset_change_not_vulnerable
      demise_change <- demise_change_not_vulnerable
    }
    
    obs_onset <- mean(cell_df_subset$onset)
    pred_onset <- obs_onset + onset_change
    obs_demise <- mean(cell_df_subset$demise)
    pred_demise <- obs_demise + demise_change

    # calculate latest planting date based on cropping intensity
    if (intensity == 'SC') {
      pred_latest_plant <- pred_demise + 30 - SC_cycle_length # assume use 20 days of soil moisture and 10 days for grain drying
      obs_latest_plant <- obs_demise + 30 - SC_cycle_length
    }
    
    if (intensity == 'DC') {
      pred_latest_plant <- pred_demise + 30 - DC_cycle_length
      obs_latest_plant <- obs_demise + 30 - DC_cycle_length
    }
    
    print(paste('too late to plant:', pred_latest_plant))
  
    for (percentile in c('percentile5', 'percentile25', 'percentile50', 'percentile75', 'percentile95')) {
      
      percentile_int <-  strtoi(str_remove(percentile, 'percentile'))
      
      # take average of each percentile observed in the region x year
      mean_observed <- mean(cell_df_subset[cell_df_subset$percentile == percentile, 'plant'])
      
      # predictions
      plant_pred_onset_change <- mean_observed + onset_change*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "onset_coef"]
      plant_pred_onset_year_change <- mean_observed + onset_change*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "onset_coef"] +
                                                      year_change*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "year_coef"]
      
      # to store originals and predictions
      predictions <- rbind(predictions, 
                           data.frame(
                             percentile = rep(percentile_int, 3),
                             plant = c(mean_observed, plant_pred_onset_change, plant_pred_onset_year_change),
                             type = c('observed', 'pred_onset_change', 'pred_onset_year_change')
                             )
                           )
    }
    
    #get observations
    observations <- predictions[predictions$type == 'observed',]
    percentile5_obs <- observations[observations$percentile == 5, 'plant']
    percentile25_obs <- observations[observations$percentile == 25, 'plant']
    percentile50_obs <- observations[observations$percentile == 50, 'plant']
    percentile75_obs <- observations[observations$percentile == 75, 'plant']
    percentile95_obs <- observations[observations$percentile == 95, 'plant']
      
    # calculate number of days available for planting
    window <- max(0, pred_latest_plant - pred_onset) # if latest plant is before onset, window = 0
    
    # calculate change in plant
    for (pred_type in c('pred_onset_change', 'pred_onset_year_change')) {
      predictions_pred_type <- predictions[predictions$type == pred_type,]

      # get predictions
      percentile5_pred <- predictions_pred_type[predictions_pred_type$percentile == 5, 'plant']
      percentile25_pred <- predictions_pred_type[predictions_pred_type$percentile == 25, 'plant']
      percentile50_pred <- predictions_pred_type[predictions_pred_type$percentile == 50, 'plant']
      percentile75_pred <- predictions_pred_type[predictions_pred_type$percentile == 75, 'plant']
      percentile95_pred <- predictions_pred_type[predictions_pred_type$percentile == 95, 'plant']
      
      # calculate area (in planting date)
      area <- 0.2*((percentile95_pred - percentile95_obs) + (percentile75_pred - percentile75_obs))/2 +
            0.25*((percentile75_pred - percentile75_obs) + (percentile50_pred - percentile50_obs))/2 +
            0.25*((percentile50_pred - percentile50_obs) + (percentile25_pred - percentile25_obs))/2 +
            0.2*((percentile25_pred - percentile25_obs) + (percentile5_pred - percentile5_obs))/2
      
      # percent people who need to plant later due to delayed onset
      if (pred_onset <= percentile5_pred) {
        percent_affect_late_onset <- 0
      }
      else {
        percent_affect_late_onset <- approx(c(percentile5_pred, percentile25_pred, percentile50_pred, percentile75_pred, percentile95_pred), 
                                            c(5, 25, 50, 75, 95), xout = pred_onset)$y
      }
      
      # percent people who can't double crop due to accelerated demise (compared to 2014 observed planting and demise)
      if (pred_latest_plant >= percentile95_pred) {
        percent_affected_early_demise <- 0
      }
      else if (pred_latest_plant <= percentile5_pred) {
        percent_affected_early_demise <- 100
      }
      else {
        # # percent of currently cropped DC who technically shouldn't be able to do DC
        # obs_percent_affected <- approx(c(percentile5_obs, percentile25_obs, percentile50_obs, percentile75_obs, percentile95_obs), 
        #                                     c(5, 25, 50, 75, 95), xout = obs_latest_plant)$y
        # 
        # # percent of currently cropped DC who won't be able to do DC in the future
        # pred_percent_affected <- approx(c(percentile5_pred, percentile25_pred, percentile50_pred, percentile75_pred, percentile95_pred), 
        #                                     c(5, 25, 50, 75, 95), xout = pred_latest_plant)$y
        # 
        # # change in percent of people who won't be able to do DC
        # percent_affected_early_demise <- pred_percent_affected - obs_percent_affected
        
        percent_affected_early_demise <- 100 - approx(c(percentile5_pred, percentile25_pred, percentile50_pred, 
                                                        percentile75_pred, percentile95_pred), 
                                            c(5, 25, 50, 75, 95), xout = pred_latest_plant)$y
      }
      
      # max change in onset needed for 5th and 50th percentile planting to touch onset, and the likelihood of that onset value
      # interpolate to find likelihood of the delta_onset. NOTE, took 100 - percentile to get likelihood of onset touching 5th percentile plant OR WORSE
      # because some of obs planting 'can't do DC', didn't find max change in demise needed for 95th percentile planting to no longer be able to do DC
      coef_onset_5thpercentile <- coefs_onset_oi[coefs_onset_oi$intensity == intensity & coefs_onset_oi$percentile == "percentile5", "onset_coef"]
      coef_year_5thpercentile <- coefs_onset_oi[coefs_onset_oi$intensity == intensity & coefs_onset_oi$percentile == "percentile5", "year_coef"]
      coef_onset_50thpercentile <- coefs_onset_oi[coefs_onset_oi$intensity == intensity & coefs_onset_oi$percentile == "percentile50", "onset_coef"]
      coef_year_50thpercentile <- coefs_onset_oi[coefs_onset_oi$intensity == intensity & coefs_onset_oi$percentile == "percentile50", "year_coef"]

      if (pred_type == 'pred_onset_change') {
        delta_onset_touching5thpercentile <- (obs_onset - percentile5_obs)/(coef_onset_5thpercentile - 1)#(percentile5_obs - coef_onset_5thpercentile*obs_onset)/(1 - coef_onset_5thpercentile) - obs_onset
        delta_onset_touching50thpercentile <- (percentile50_obs - coef_onset_50thpercentile*obs_onset)/(1 - coef_onset_50thpercentile) - obs_onset
        
        delta_onset_likelihood_touching5thpercentile <- 100 - 
                                              approx(x = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset'],
                                               y = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset_percentile'], 
                                               xout = delta_onset_touching5thpercentile)$y
        
        delta_onset_likelihood_touching50thpercentile <- 100 - 
                                              approx(x = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset'],
                                               y = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset_percentile'], 
                                               xout = delta_onset_touching50thpercentile)$y
      }
      if (pred_type == 'pred_onset_year_change') {
        delta_onset_touching5thpercentile <- (obs_onset - percentile5_obs -  coef_year_5thpercentile*10)/(coef_onset_5thpercentile - 1)
                                              #          coef_year_5thpercentile*10)/(1 - coef_onset_5thpercentile)
                                                #(percentile5_obs - coef_onset_5thpercentile*obs_onset + 
                                              #          coef_year_5thpercentile*10)/(1 - coef_onset_5thpercentile) - obs_onset
        delta_onset_touching50thpercentile <- (percentile50_obs - coef_onset_50thpercentile*obs_onset + 
                                                        coef_year_50thpercentile*10)/(1 - coef_onset_50thpercentile) - obs_onset
        
        delta_onset_likelihood_touching5thpercentile <- 100 - 
                                               approx(x = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset'],
                                               y = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset_percentile'], 
                                               xout = delta_onset_touching5thpercentile)$y
        
        delta_onset_likelihood_touching50thpercentile <- 100 - 
                                               approx(x = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset'],
                                               y = delta_onset_predictions[delta_onset_predictions$region == region, 'delta_onset_percentile'], 
                                               xout = delta_onset_touching50thpercentile)$y
      }
      
      print(paste('intensity', intensity, 'region', region))
      
      new_predictions_summary_row <- data.frame(intensity = intensity,
                                              region = region,
                                              pred_type = pred_type,
                                              change_plant = area,
                                              percent_affect_late_onset = percent_affect_late_onset, 
                                              percent_affected_early_demise = percent_affected_early_demise,
                                              window = window,
                                              delta_onset_touching5thpercentile = delta_onset_touching5thpercentile,
                                              delta_onset_likelihood_touching5thpercentile = delta_onset_likelihood_touching5thpercentile,
                                              delta_onset_touching50thpercentile = delta_onset_touching50thpercentile,
                                              delta_onset_likelihood_touching50thpercentile = delta_onset_likelihood_touching50thpercentile
                                              )
      
      predictions_summary <- rbind(predictions_summary, new_predictions_summary_row)

    }

    # set max x limit based on cropping intensity
    if (intensity == 'SC') {max_xlim <- 230}
    if (intensity == 'DC') {max_xlim <- 130}
    
    # for plotting, interpolate predicted plant to pred_onset and pred_latest_plant, then 
    #filter predictions to be only between pred_onset and pred_latest_plant (for plotting)
    predictions_filtered <- predictions # to save interpolated and filtered results
    for (type in c('pred_onset_change', 'pred_onset_year_change')) {
      
      # get percentile and planting date
      pred_percentile <- predictions[predictions$type == type, 'percentile']
      pred_plant <- predictions[predictions$type == type, 'plant']
      
      # interpolate the planting percentile at onset and latest plant dates
      onset_percentile <- approx(pred_plant, pred_percentile, xout = pred_onset)$y
      latest_plant_percentile <- approx(pred_plant, pred_percentile, xout = pred_latest_plant)$y
      
      # add interpolated points to predictions_filtered
      predictions_filtered <- rbind(predictions_filtered, data.frame(percentile = c(onset_percentile, latest_plant_percentile), 
                                             plant = c(pred_onset, pred_latest_plant), 
                                             type = type))

    }
    
    # filter predicted CDF lines, but not the observed line
    predictions_filtered <- rbind(predictions_filtered[predictions_filtered$plant >= pred_onset & 
                                                   predictions_filtered$plant <= pred_latest_plant & 
                                                   predictions_filtered$type != 'observed',],
                                  predictions[predictions$type == 'observed' ,])
    
    # plotting aesthetics
    transparency_onset_demise_lines <- 0.8
    transparency_arrows <- 0.8
    cdf_line_width <- 2
    
    # predictions plot (full)
    predictions_plot <- ggplot(predictions) +
      geom_line(mapping = aes(x = plant, y = percentile, col = type), size = cdf_line_width, alpha = 0.3) + # more transparent
      geom_line(data = predictions_filtered, mapping = aes(x = plant, y = percentile, col = type), size = cdf_line_width, alpha = 0.8) + # less transparent, for only between onset and too late to plant
      scale_color_manual(values=c("black", '#EC7063', '#B9770E')) + # observed, no trend, trend cdf lines
      #geom_point(mapping = aes(x = plant, y = percentile, col = type)) +
      geom_vline(mapping = aes(xintercept = obs_onset), col = '#3498DB', size = 1, alpha = transparency_onset_demise_lines) + # observed onset
      geom_vline(mapping = aes(xintercept = pred_onset), col = '#3498DB', linetype = 'dashed',  
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted onset
      geom_vline(mapping = aes(xintercept = obs_latest_plant), col = '#1B4F72',  size = 1, alpha = transparency_onset_demise_lines) + # observed latest plant
      geom_vline(mapping = aes(xintercept = pred_latest_plant), col = '#1B4F72', linetype = 'dashed', 
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted latest plant
      geom_segment(aes(x=obs_onset, xend=pred_onset, y=60, yend=60), size = 1, color = '#3498DB', alpha = transparency_arrows,
                   arrow = arrow(type="closed",ends="last",length=unit(0.3,"cm"))) +
      geom_segment(aes(x=obs_latest_plant, xend=pred_latest_plant, y=40, yend=40), size = 1, color = '#21618C', alpha = transparency_arrows,
                   arrow = arrow(type="closed",ends="last",length=unit(0.3,"cm"))) +
      ggtitle(paste('Planting CDF',intensity, region, 'region', 'case', case_name)) +
      xlab('Days after Aug 1') + 
      xlim(40, 130) + # full axis: 30 to max_xlim
      theme_bw() +
      theme(panel.grid = element_blank(), 
            axis.text.x = element_text(face="bold", size=12), # size for subplot = 14, size for fullplot = 12
            axis.text.y = element_text(face="bold", size=12),
            axis.title = element_text(size=12)
            )
    
    # predictions subplot (to show close-up of predicted cdfs)
    predictions_subplot <- ggplot(predictions) +
      geom_line(mapping = aes(x = plant, y = percentile, col = type), size = cdf_line_width, alpha = 0.3) + # more transparent
      geom_line(data = predictions_filtered, mapping = aes(x = plant, y = percentile, col = type), size = cdf_line_width, alpha = 0.8) + # less transparent, for only between onset and too late to plant
      scale_color_manual(values=c("black", '#EC7063', '#B9770E')) + # observed, no trend, trend cdf lines
      geom_vline(mapping = aes(xintercept = obs_onset), col = '#3498DB', size = 1, alpha = transparency_onset_demise_lines) + # observed onset
      geom_vline(mapping = aes(xintercept = pred_onset), col = '#3498DB', linetype = 'dashed',  
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted onset
      geom_vline(mapping = aes(xintercept = obs_latest_plant), col = '#1B4F72',  size = 1, alpha = transparency_onset_demise_lines) + # observed latest plant
      geom_vline(mapping = aes(xintercept = pred_latest_plant), col = '#1B4F72', linetype = 'dashed', 
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted latest plant
      geom_segment(aes(x=obs_onset, xend=pred_onset, y=60, yend=60), size = 1, color = '#3498DB', alpha = transparency_arrows, 
                   arrow = arrow(type="closed",ends="last",length=unit(0.3,"cm"))) +
      geom_segment(aes(x=obs_latest_plant, xend=pred_latest_plant, y=40, yend=40), size = 1, color = '#21618C', alpha = transparency_arrows, 
                   arrow = arrow(type="closed",ends="last",length=unit(0.3,"cm"))) +
      ggtitle(paste('SUBPLOT Planting CDF',intensity, region, 'region', 'case', case_name)) +
      xlab('Days after Aug 1') + 
      xlim(50, 130) + # full axis: 30 to max_xlim
      theme_bw() +
      theme(panel.grid = element_blank(), 
            axis.text.x = element_text(face="bold", size=12), # size for subplot = 15, size for fullplot = 12
            axis.text.y = element_text(face="bold", size=12),
            axis.title = element_text(size=12)
            )
    
    # this plot is to demonstrate the metric of 'available' change in onset before 5th percentile planting is touched
    # get the 'available' onset change for trend and no trend cases
    onset_change_available_trend <- predictions_summary[predictions_summary$intensity == intensity & 
                                                          predictions_summary$region == region & 
                                                          predictions_summary$pred_type == 'pred_onset_year_change', 
                                                        'delta_onset_touching5thpercentile']
    onset_change_available_notrend <- predictions_summary[predictions_summary$intensity == intensity & 
                                                          predictions_summary$region == region & 
                                                          predictions_summary$pred_type == 'pred_onset_change', 
                                                        'delta_onset_touching5thpercentile']
    
    # this stores THEORETICAL planting CDFs in the case that the available onset change happens
    predictions_avail_onset_change <- data.frame(percentile = numeric(0),
                                                   plant = numeric(0),
                                                   type = numeric(0))
    
    # predict planting dates assuming the available onset change happens
    for (percentile in c('percentile5', 'percentile25', 'percentile50', 'percentile75', 'percentile95')) {
      
      percentile_int <-  strtoi(str_remove(percentile, 'percentile'))
      
      # take average of each percentile observed in the region x year
      mean_observed <- predictions[predictions$percentile == percentile_int & predictions$type == 'observed', 'plant']
      
      # predictions
      plant_pred_onset_change <- mean_observed + onset_change_available_notrend*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "onset_coef"]
      plant_pred_onset_year_change <- mean_observed + onset_change_available_trend*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "onset_coef"] +
                                                      year_change*coefs_onset_oi[coefs_onset_oi$intensity == intensity &
                                                                                       coefs_onset_oi$percentile == percentile, "year_coef"]

      # to store originals and predictions
      predictions_avail_onset_change <- rbind(predictions_avail_onset_change, 
                           data.frame(
                             percentile = rep(percentile_int, 3),
                             plant = c(mean_observed, plant_pred_onset_change, plant_pred_onset_year_change),
                             type = c('observed', 'pred_onset_change', 'pred_onset_year_change')
                             )
                           )
    }
    
    predictions_plot_avail_onset_change <- ggplot(predictions_avail_onset_change) +
      geom_line(mapping = aes(x = plant, y = percentile, col = type), size = cdf_line_width) + # more transparent
      scale_color_manual(values=c("black", '#EC7063', '#B9770E')) + # observed, no trend, trend cdf lines
      #geom_point(mapping = aes(x = plant, y = percentile, col = type)) +
      geom_vline(mapping = aes(xintercept = obs_onset), col = '#3498DB', size = 1, alpha = transparency_onset_demise_lines) + # observed onset
      geom_vline(mapping = aes(xintercept = obs_onset + onset_change_available_trend), col = '#3498DB', linetype = 'dashed',  
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted onset
      geom_vline(mapping = aes(xintercept = obs_onset + onset_change_available_notrend), col = '#3498DB', linetype = 'dashed', 
                 size = 1, alpha = transparency_onset_demise_lines) + # predicted latest plant
      ggtitle(paste('Planting CDF',intensity, region, 'region', 'available onset change')) +
      xlab('Days after Aug 1') + 
      xlim(40, 130) + # full axis: 30 to max_xlim
      theme_bw() +
      theme(panel.grid = element_blank(), 
            axis.text.x = element_text(face="bold", size=12), # size for subplot = 14, size for fullplot = 12
            axis.text.y = element_text(face="bold", size=12),
            axis.title = element_text(size=12)
            )
    
    print(predictions_plot)
    print(predictions_plot_avail_onset_change)
    #print(predictions_subplot)
  }
}

#print(predictions_summary)

```

## heatmap of predicted metrics

```{r}

# sample_predicted <- data.frame(case = c('worst', 'worst', 'medium', 'medium', 'best', 'best',
#                                             'worst', 'worst', 'medium', 'medium', 'best', 'best',
#                                             'worst', 'worst', 'medium', 'medium', 'best', 'best',
#                                             'worst', 'worst', 'medium', 'medium', 'best', 'best'),
#                           intensity = c('SC', 'DC', 'SC', 'DC', 'SC', 'DC',
#                                         'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
#                                         'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
#                                         'SC', 'DC', 'SC', 'DC', 'SC', 'DC'), 
#                           region = c('east', 'east', 'east', 'east', 
#                                      'east', 'east', 'east', 'east',
#                                      'east', 'east', 'east', 'east',
#                                      'west', 'west', 'west', 'west',
#                                      'west', 'west', 'west', 'west',
#                                      'west', 'west', 'west', 'west'),
#                           trend = c('yes', 'yes', 'yes', 'yes', 'yes', 'yes',
#                                     'no', 'no', 'no', 'no', 'no', 'no',
#                                     'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
#                                     'no', 'no', 'no', 'no', 'no', 'no'),
#                           value = c(1,2,3,4,5,6,
#                                     7,8,9,10,11,12,
#                                     13, 14, 15, 16, 17, 18,
#                                     19, 20, 21, 22, 23, 24
#                                     ))
# sample_predicted$yID<- with(sample_predicted, paste0(case, intensity))
# sample_predicted$xID<- with(sample_predicted, paste0(region, trend))
# 
# print(sample_predicted)
# 
# ggplot(data = sample_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
#   geom_tile() +
#   geom_text(aes(fill = sample_predicted$value, label = round(sample_predicted$value, 2))) + # write the values
#   xlab(label = "Sample") +
#   ggtitle("Metric name")

plant_delay_days_predicted <- data.frame(case = c('worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best'),
                          intensity = c('SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east', 
                                     'east', 'east', 'east', 'east',
                                     'east', 'east', 'east', 'east',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no',
                                    'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no'),
                          value = c(-14.2, -7.82, -15.94, -11.53, -17.96, -15.85,
                                    2.62, 5.59, 0.87, 1.87, -1.14, -2.44,
                                    -15.11, -9.76, -12.36, -16.33, -17.37, -14.6,
                                    1.71, 3.64, 1.04, 0.49, -0.56, -1.19
                                    ))
plant_delay_days_predicted$yID<- with(plant_delay_days_predicted, paste0(case, intensity))
plant_delay_days_predicted$xID<- with(plant_delay_days_predicted, paste0(region, trend))

plant_delay_percent_predicted <- data.frame(case = c('worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best'),
                          intensity = c('SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east', 
                                     'east', 'east', 'east', 'east',
                                     'east', 'east', 'east', 'east',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no',
                                    'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no'),
                          value = c(44.91, 61.35, 18.33, 24.14, 0, 0,
                                    0, 6.77, 0, 0, 0, 0,
                                    44.81, 53.22, 23.02, 24.02, 13.07, 13.64,
                                    0, 0, 0, 0, 0, 0
                                    ))
plant_delay_percent_predicted$yID<- with(plant_delay_percent_predicted, paste0(case, intensity))
plant_delay_percent_predicted$xID<- with(plant_delay_percent_predicted, paste0(region, trend))

DC_not_possible_predicted <- data.frame(case = c('worst', 'medium', 'best',
                                                 'worst', 'medium', 'best',
                                                 'worst', 'medium', 'best',
                                                 'worst', 'medium', 'best'),
                          region = c('east', 'east', 'east', 'east', 'east', 'east', 
                                     'west', 'west', 'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'yes', 
                                    'no', 'no', 'no', 
                                    'yes', 'yes', 'yes', 
                                    'no', 'no', 'no'),
                          value = c(73.86, 11.98, 0, 100, 42.18, 8.95, 
                                    21.07, 0, 0, 75.26, 9.49, 0))
DC_not_possible_predicted$yID<- with(DC_not_possible_predicted, paste0(case))
DC_not_possible_predicted$xID<- with(DC_not_possible_predicted, paste0(region, trend))

plant_window_predicted <- data.frame(case = c('worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best'),
                          intensity = c('SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east', 
                                     'east', 'east', 
                                     'west', 'west', 'west', 'west',
                                     'west', 'west'),
                          value = c(101.34, 0, 133.99, 23.99, 161.9, 51.9,
                                    118.5, 8.48, 147.35, 37.35, 169.36, 59.36))
plant_window_predicted$yID<- with(plant_window_predicted, paste0(case, intensity))
plant_window_predicted$xID<- with(plant_window_predicted, paste0(region))

delta_onset_touching5thpercentile_predicted <- data.frame(
                          intensity = c('SC', 'DC', 'SC', 'DC', 
                                        'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east',
                                     'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no'),
                          value = c(-3.93, -6.66, 25.18, 20.02, -11.88, -12.02, 17.22, 14.66))
delta_onset_touching5thpercentile_predicted$yID<- delta_onset_touching5thpercentile_predicted$intensity
delta_onset_touching5thpercentile_predicted$xID<- with(delta_onset_touching5thpercentile_predicted, paste0(region, trend))

delta_onset_likelihood_predicted <- data.frame(
                          intensity = c('SC', 'DC', 'SC', 'DC', 
                                        'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east',
                                     'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'no', 'no', 'yes', 'yes', 'no', 'no'),
                          value = c(82.15, 86.92, 0.13, 8.19, 100, 100, 0, 6.22))
delta_onset_likelihood_predicted$yID<- delta_onset_likelihood_predicted$intensity
delta_onset_likelihood_predicted$xID<- with(delta_onset_likelihood_predicted, paste0(region, trend))

# summary metric: the percent of soy that's NOT affected by delayed onset OR earlier demise max(0, 1 - % infeasible DC - % delay)
plant_percent_affected_predicted <- data.frame(case = c('worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best',
                                            'worst', 'worst', 'medium', 'medium', 'best', 'best'),
                          intensity = c('SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC',
                                        'SC', 'DC', 'SC', 'DC', 'SC', 'DC'), 
                          region = c('east', 'east', 'east', 'east', 
                                     'east', 'east', 'east', 'east',
                                     'east', 'east', 'east', 'east',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west',
                                     'west', 'west', 'west', 'west'),
                          trend = c('yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no',
                                    'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
                                    'no', 'no', 'no', 'no', 'no', 'no'),
                          value = c(44.91, 100, 18.33, 24.14 + 12, 0, 0,
                                    0, 100, 0, 42, 0, 9,
                                    44.81, 53.22 + 21, 23.02, 24.02, 13.07, 13.64,
                                    0, 75, 0, 9, 0, 0
                                    ))
plant_percent_affected_predicted$yID<- with(plant_percent_affected_predicted, paste0(case, intensity))
plant_percent_affected_predicted$xID<- with(plant_percent_affected_predicted, paste0(region, trend))

text_size <- 10
ggplot(data = plant_delay_days_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(plant_delay_days_predicted$value, 0)), size = text_size) + # write the values
  scale_fill_gradient2(name = "Days", low = "blue", high = "red", midpoint = 0) +
  ggtitle("Average delay in planting date in average 25km cell") +
  theme_bw()

ggplot(data = plant_delay_percent_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(plant_delay_percent_predicted$value, 0)), size = text_size) + # write the values
  scale_fill_gradient2(name = "Percent", low = "white", high = "red") +
  ggtitle("Percent planting that must be delayed in average 25km cell") +
  theme_bw()

ggplot(data = DC_not_possible_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(DC_not_possible_predicted$value, 0)), size = text_size) + # write the values
  scale_fill_gradient2(name = "Percent", low = "white", high = "red") +
  ggtitle("Percent double cropping that's infeasible in average 25km cell") +
  theme_bw()

ggplot(data = plant_window_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  #geom_text(aes(label = round(plant_window_predicted$value, 0)), size = text_size) + # write the values
  #scale_fill_gradient(name = "Days", low = "red", high = "blue") +
  scale_fill_gradient2(name = "Days", low = "red", high = "#8D88E2", midpoint = 45) +
  ggtitle("Planting window in average 25km cell") +
  theme_bw()

ggplot(data = delta_onset_touching5thpercentile_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(delta_onset_touching5thpercentile_predicted$value, 1)), size = 5) + # write the values
  scale_fill_gradient2(name = "Days", low = "red", high = "blue", midpoint = 0) +
  ggtitle("Onset change at which planting dates experience hard limit [days]") +
  theme_bw()

ggplot(data = delta_onset_likelihood_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(delta_onset_likelihood_predicted$value, 1)), size = text_size) + # write the values
  scale_fill_gradient(name = "Days", low = "red", high = "white") +
  ggtitle("Probability that onset will become hard limit for planting [%]") +
  theme_bw()

ggplot(data = plant_percent_affected_predicted, mapping = aes(x = xID, y = yID, fill = value)) +
  geom_tile() +
  geom_text(aes(label = round(plant_percent_affected_predicted$value, 0)), size = text_size) + # write the values
  scale_fill_gradient(name = "Percent", low = "white", high = "red") +
  ggtitle("Percent planting affected by both onset and demise as hard limit in average 25km cell") +
  theme_bw()
```


# correlation between onset and demise
```{r}

library(fmsb) # calculate percentile

corr_nw <- cor.test(nw_predictions$onset, nw_predictions$demise)
corr_ne <- cor.test(ne_predictions$onset, ne_predictions$demise)
corr_nw_est <- round(corr_nw$estimate, 3)[1]
corr_ne_est <- round(corr_ne$estimate, 3)[1]
corr_nw_pval <- round(corr_nw$p.value, 3)
corr_ne_pval <- round(corr_ne$p.value, 3)

corr_nw_plot <- ggplot(nw_predictions, aes(x = onset, y = demise)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ggtitle('Northwest MT') +
  annotate("text", x = 25, y = 250, color = "red", 
           label = paste0("Pearson correlation: ", corr_nw_est, ", \n p-value: ", corr_nw_pval)) +
  theme_bw()

corr_ne_plot <- ggplot(ne_predictions, aes(x = onset, y = demise)) +
  geom_point() +
  geom_smooth(method=lm, se=FALSE) +
  ggtitle('Northeast MT') +
  annotate("text", x = 30, y = 220, color = "red", 
           label = paste0("Pearson correlation: ", corr_ne_est, ", \n p-value: ", corr_ne_pval)) +
  theme_bw()

print(corr_nw_plot)
print(corr_ne_plot)

# figure out if we want medium or late onset to pair with early, medium demise
# convert onset, demise into percentiles
nw_predictions$onset_percentile <- percentile(nw_predictions$onset)
nw_predictions$demise_percentile <- percentile(nw_predictions$demise)
nw_predictions$length_percentile <- percentile(nw_predictions$length)

ne_predictions$onset_percentile <- percentile(ne_predictions$onset)
ne_predictions$demise_percentile <- percentile(ne_predictions$demise)
ne_predictions$length_percentile <- percentile(ne_predictions$length)

# get 10th, 50th, 90th percentile demise, and for those years, get the onset percentile
nw_lateDemise_onsetPer <- nw_predictions[nw_predictions$demise_percentile >= 85 & 
                                          nw_predictions$demise_percentile <= 95, 
                                       'onset_percentile']

ne_lateDemise_onsetPer <- ne_predictions[ne_predictions$demise_percentile >= 85 & 
                                          ne_predictions$demise_percentile <= 95, 
                                       'onset_percentile']

nw_medDemise_onsetPer <- nw_predictions[nw_predictions$demise_percentile >= 45 & 
                                          nw_predictions$demise_percentile <= 55, 
                                       'onset_percentile']

ne_medDemise_onsetPer <- ne_predictions[ne_predictions$demise_percentile >= 45 & 
                                          ne_predictions$demise_percentile <= 55, 
                                       'onset_percentile']

nw_earlyDemise_onsetPer <- nw_predictions[nw_predictions$demise_percentile >= 5 & 
                                          nw_predictions$demise_percentile <= 15, 
                                       'onset_percentile']

ne_earlyDemise_onsetPer <- ne_predictions[ne_predictions$demise_percentile >= 5 & 
                                          ne_predictions$demise_percentile <= 15, 
                                       'onset_percentile']

nw_onset_demise_pairing <- rbind(data.frame(demise_percentile = 'late', 
                                            onset_percentile = nw_lateDemise_onsetPer),
                                  data.frame(demise_percentile = 'middle', 
                                            onset_percentile = nw_medDemise_onsetPer),
                                 data.frame(demise_percentile = 'early', 
                                            onset_percentile = nw_earlyDemise_onsetPer))
nw_onset_demise_pairing$demise_percentile <- as.factor(nw_onset_demise_pairing$demise_percentile)

ne_onset_demise_pairing <- rbind(data.frame(demise_percentile = 'late', 
                                            onset_percentile = ne_lateDemise_onsetPer),
                                 data.frame(demise_percentile = 'middle', 
                                            onset_percentile = ne_medDemise_onsetPer),
                                 data.frame(demise_percentile = 'early', 
                                            onset_percentile = ne_earlyDemise_onsetPer))
ne_onset_demise_pairing$demise_percentile <- as.factor(ne_onset_demise_pairing$demise_percentile)

nw_onset_demise_boxplot <- ggplot(nw_onset_demise_pairing, aes(x = demise_percentile, y = onset_percentile)) +
  geom_boxplot() +
  geom_hline(yintercept=50, linetype="dashed", color = "blue") +
  xlab('Demise category') +
  ylab('Onset percentile') +
  ggtitle('Northwest MT') +
  theme_bw()

ne_onset_demise_boxplot <- ggplot(ne_onset_demise_pairing, aes(x = demise_percentile, y = onset_percentile)) +
  geom_boxplot() +
  geom_hline(yintercept=50, linetype="dashed", color = "blue") +
  xlab('Demise category') +
  ylab('Onset percentile') +
  ggtitle('Northeast MT') +
  theme_bw()

print(nw_onset_demise_boxplot)
print(ne_onset_demise_boxplot)

```