---
title: "timeseries-testing"
output: html_document
---

## Read in timeseries and clean

```{r}

library(imputeTS)
library(dplyr)

ts <- read.csv('point15.csv')[,1:3]
colnames(ts) <- c('date', 'EVI_raw', 'EVI')
ts$date <- as.Date(ts$date, '%d-%h-%y')
ts$day <- as.numeric(ts$date - as.Date('2016-08-01')) # number of days
ts$EVI <- na.interpolation(ts$EVI)
ts <- ts %>% select(-c(EVI_raw)) %>% # don't need EVI_raw column
         distinct()


year <- 2017
year_start = year - 1
year_end = year

```

## Savitsky-Golay fitting

```{r}
library(signal) # Savitsky-Golay fitting

# TARGET THE APPROPRIATE TIME PERIOD FOR FITTING
# find index of important dates, use to target specific parts of the year
targeted_start_day <- as.numeric(as.Date('2016-10-01') - as.Date('2016-08-01'))
targeted_end_day <- as.numeric(as.Date('2017-07-01') - as.Date('2016-08-01'))
targeted_days <- which(ts$day >= targeted_start_day & ts$day <= targeted_end_day) # index of days to target

EVI <- ts$EVI[targeted_days]
t <- ts$day[targeted_days]

# Savitsky-Golay filter
EVI_SG <- sgolayfilt(EVI, p = 2)

# find phenological dates, first make sure the dates found are for first crop, first or second half
firstHalf_dates <- which(t >= 60 & t <= 140) # rising limb of first crop
t_firstHalf <- t[firstHalf_dates]
fittedEVI_firstHalf <- EVI_SG[firstHalf_dates]

secondHalf_dates <- which(t >= 140 & t <= 220) # falling limb of first crop
t_secondHalf <- t[secondHalf_dates]
fittedEVI_secondHalf <- EVI_SG[secondHalf_dates]

firstCrop_dates <- which(t >= 60 & t <= 220) # first crop
t_firstCrop <- t[firstCrop_dates]
fittedEVI_firstCrop <- EVI_SG[firstCrop_dates]

# date and value of max EVI
maxEVI <- max(fittedEVI_firstCrop)
minEVI_left <- min(fittedEVI_firstHalf)
minEVI_right <- min(fittedEVI_secondHalf)

date_min = approx(x = fittedEVI_firstCrop, y = t_firstCrop, xout = minEVI_left)

# find phenological dates
startOfSeasonEVI <- 0.1*(maxEVI - minEVI_left) + minEVI_left
endOfSeasonEVI <- 0.1*(maxEVI - minEVI_right) + minEVI_right

rightOfPeakEVI <- 0.9*(maxEVI - minEVI_left) + minEVI_left
leftOfPeakEVI <- 0.9*(maxEVI - minEVI_right) + minEVI_right

date_startOfSeason <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = startOfSeasonEVI)
date_endOfSeason <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = endOfSeasonEVI)

date_rightOfPeak <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = rightOfPeakEVI)
date_leftOfPeak <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = leftOfPeakEVI)
midSeason <- mean(c(date_rightOfPeak$y, date_leftOfPeak$y))

quarter_period1 <- (date_endOfSeason$y - date_startOfSeason$y)/4
quarter_period2 <- (midSeason - date_startOfSeason$y)/2
quarter_period3 <- (date_endOfSeason$y - midSeason)/2
quarter_period_comparable <- (midSeason - date_min$y)/2
mean_quarter_period = mean(c(quarter_period1, quarter_period2, quarter_period3))

print(c('date_startOfSeason', date_startOfSeason$y))
print(c('date_endOfSeason', date_endOfSeason$y))
print(c('midSeason', midSeason))
print(c('q pd 1', quarter_period1))
print(c('q pd 2', quarter_period2))
print(c('q pd 3', quarter_period3))
print(c('mean qpd', mean_quarter_period))
print(c('comparable quarter period', quarter_period_comparable))

```

## Harmonic fitting with estimated omega

```{r}

# TARGET THE APPROPRIATE TIME PERIOD FOR FITTING
# find index of important dates, use to target specific parts of the year
targeted_start_day <- as.numeric(as.Date('2016-10-01') - as.Date('2016-08-01'))
targeted_end_day <- as.numeric(as.Date('2017-07-01') - as.Date('2016-08-01'))
targeted_days <- which(ts$day >= targeted_start_day & ts$day <= targeted_end_day) # index of days to target

EVI <- ts$EVI[targeted_days]
t <- ts$day[targeted_days]

t_fitting <- t/(2*3.14)

# Model that estimates w
model_nls1 <- nls(EVI~c1 + c2*t_fitting + c3*(t_fitting^2) + c4*sin(w*t_fitting) + c5*cos(w*t_fitting) +
               c6*sin(2*w*t_fitting) + c7*cos(2*w*t_fitting), #+ 
               #c8*sin(3*w*t_fitting) + c9*cos(3*w*t_fitting), 
             start = list(c1 = 0.5, c2 = 0, c3 = 0, 
                          c4 = 1, c5 = 1, c6 = 1,
                          c7 = 1, #c8 = 1, c9 = 1,
                          w = 0.15
                          ),
             control = nls.control(maxiter = 500))

plot(t, EVI)
lines(t, EVI, col = "green")
lines(t, fitted(model_nls1), col = "red")

# retreive omega from estimated coefficients
omega <- summary(model_nls1)$parameters[8]
quarter_period <- 3.14/(2*omega)
period <- 2*3.14/omega

# find phenological dates, first make sure the dates found are for first crop, first or second half
firstHalf_dates <- which(t >= 60 & t <= 140) # rising limb of first crop
t_firstHalf <- t[firstHalf_dates]
fittedEVI_firstHalf <- fitted(model_nls1)[firstHalf_dates]

secondHalf_dates <- which(t >= 140 & t <= 220) # falling limb of first crop
t_secondHalf <- t[secondHalf_dates]
fittedEVI_secondHalf <- fitted(model_nls1)[secondHalf_dates]

firstCrop_dates <- which(t >= 60 & t <= 220) # first crop
t_firstCrop <- t[firstCrop_dates]
fittedEVI_firstCrop <- fitted(model_nls1)[firstCrop_dates]

# date and value of max EVI
maxEVI <- max(fittedEVI_firstCrop)
minEVI_left <- min(fittedEVI_firstHalf)
minEVI_right <- min(fittedEVI_secondHalf)

date_min = approx(x = fittedEVI_firstCrop, y = t_firstCrop, xout = minEVI_left)

# find phenological dates
startOfSeasonEVI <- 0.1*(maxEVI - minEVI_left) + minEVI_left
endOfSeasonEVI <- 0.1*(maxEVI - minEVI_right) + minEVI_right

rightOfPeakEVI <- 0.9*(maxEVI - minEVI_left) + minEVI_left
leftOfPeakEVI <- 0.9*(maxEVI - minEVI_right) + minEVI_right

date_startOfSeason <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = startOfSeasonEVI)
date_endOfSeason <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = endOfSeasonEVI)

date_rightOfPeak <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = rightOfPeakEVI)
date_leftOfPeak <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = leftOfPeakEVI)
midSeason <- mean(c(date_rightOfPeak$y, date_leftOfPeak$y))

quarter_period1 <- (date_endOfSeason$y - date_startOfSeason$y)/4
quarter_period2 <- (midSeason - date_startOfSeason$y)/2
quarter_period3 <- (date_endOfSeason$y - midSeason)/2
quarter_period_comparable <- (midSeason - date_min$y)/2
mean_quarter_period = mean(c(quarter_period1, quarter_period2, quarter_period3))

print(c('date_startOfSeason', date_startOfSeason$y))
print(c('date_endOfSeason', date_endOfSeason$y))
print(c('midSeason', midSeason))
print(c('q pd 1', quarter_period1))
print(c('q pd 2', quarter_period2))
print(c('q pd 3', quarter_period3))
print(c('mean qpd', mean_quarter_period))
print(c('comparable quarter period', quarter_period_comparable))

```

## Harmonic fitting exactly as in TIMESAT

```{r}

# TARGET THE APPROPRIATE TIME PERIOD FOR FITTING
# find index of important dates, use to target specific parts of the year
targeted_start_day <- as.numeric(as.Date('2016-10-01') - as.Date('2016-08-01'))
targeted_end_day <- as.numeric(as.Date('2017-07-01') - as.Date('2016-08-01'))
targeted_days <- which(ts$day >= targeted_start_day & ts$day <= targeted_end_day) # index of days to target

EVI <- ts$EVI[targeted_days]
t <- ts$day[targeted_days]

wt <- (6*3.14/length(ts$day))*t/(2*3.14)

# Model that sets w (as in TIMESAT)
model_nls2 <- nls(EVI~c1 + c2*t + c3*(t^2) + c4*sin(wt) + c5*cos(wt) +
               c6*sin(2*wt) + c7*cos(2*wt) + 
               c8*sin(3*wt) + c9*cos(3*wt), 
             start = list(c1 = 0.5, c2 = 0, c3 = 0, 
                          c4 = 0, c5 = 0, c6 = 0,
                          c7 = 0, c8 = 0, c9 = 0
                          ),
             control = nls.control(maxiter = 500))

plot(t, EVI)
lines(t, EVI, col = "green")
lines(t, fitted(model_nls2), col = "red")

# retreive omega from estimated coefficients
omega <- 6*3.14/length(t)
quarter_period <- 3.14/(2*omega)
period <- 2*3.14/omega

# find phenological dates, first make sure the dates found are for first crop, first or second half
firstHalf_dates <- which(t >= 60 & t <= 140) # rising limb of first crop
t_firstHalf <- t[firstHalf_dates]
fittedEVI_firstHalf <- fitted(model_nls2)[firstHalf_dates]

secondHalf_dates <- which(t >= 140 & t <= 220) # falling limb of first crop
t_secondHalf <- t[secondHalf_dates]
fittedEVI_secondHalf <- fitted(model_nls2)[secondHalf_dates]

firstCrop_dates <- which(t >= 60 & t <= 220) # first crop
t_firstCrop <- t[firstCrop_dates]
fittedEVI_firstCrop <- fitted(model_nls2)[firstCrop_dates]

# date and value of max EVI
maxEVI <- max(fittedEVI_firstCrop)
minEVI_left <- min(fittedEVI_firstHalf)
minEVI_right <- min(fittedEVI_secondHalf)

date_min = approx(x = fittedEVI_firstCrop, y = t_firstCrop, xout = minEVI_left)

# find phenological dates, need to interpolate linearly with approx
startOfSeasonEVI <- 0.1*(maxEVI - minEVI_left) + minEVI_left
endOfSeasonEVI <- 0.1*(maxEVI - minEVI_right) + minEVI_right

rightOfPeakEVI <- 0.9*(maxEVI - minEVI_left) + minEVI_left
leftOfPeakEVI <- 0.9*(maxEVI - minEVI_right) + minEVI_right

date_startOfSeason <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = startOfSeasonEVI)
date_endOfSeason <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = endOfSeasonEVI)

date_rightOfPeak <- approx(x = fittedEVI_secondHalf, y = t_secondHalf, xout = rightOfPeakEVI)
date_leftOfPeak <- approx(x = fittedEVI_firstHalf, y = t_firstHalf, xout = leftOfPeakEVI)
midSeason <- mean(c(date_rightOfPeak$y, date_leftOfPeak$y))

quarter_period1 <- (date_endOfSeason$y - date_startOfSeason$y)/4
quarter_period2 <- (midSeason - date_startOfSeason$y)/2
quarter_period3 <- (date_endOfSeason$y - midSeason)/2
quarter_period_comparable <- (midSeason - date_min$y)/2
mean_quarter_period = mean(c(quarter_period1, quarter_period2, quarter_period3))

print(c('date_startOfSeason', date_startOfSeason$y))
print(c('date_endOfSeason', date_endOfSeason$y))
print(c('midSeason', midSeason))
print(c('q pd 1', quarter_period1))
print(c('q pd 2', quarter_period2))
print(c('q pd 3', quarter_period3))
print(c('mean qpd', mean_quarter_period))
print(c('comparable quarter period', quarter_period_comparable))
```


## Finding omega: DON'T USE
# https://stats.stackexchange.com/questions/60994/fit-a-sinusoidal-term-to-data

```{r}

ssp <- spectrum(EVI)  
per <- 1/ssp$freq[ssp$spec==max(ssp$spec)]
reslm <- lm(EVI ~ sin(1/per*t)+cos(1/per*t))
summary(reslm)

rg <- diff(range(EVI))
plot(EVI~t,ylim=c(min(EVI)-0.1*rg,max(EVI)+0.1*rg))
lines(fitted(reslm)~t,col=4,lty=2)   # dashed blue line is sin fit

# including 2nd harmonic really improves the fit
reslm2 <- lm(EVI ~ sin(1/per*t)+cos(1/per*t)+sin(2/per*t)+cos(2/per*t))
summary(reslm2)
lines(fitted(reslm2)~t,col=3)    # solid green line is periodic with second harmonic

print('period')
print(per)

```

## Harmonic fitting via Clinton method: DOESN'T ESTIMATE OMEGA. THIS SECTION IS WRONG

```{r}
library(HarmonicRegression)

# find index of important dates, use to target specific parts of the year
targeted_start_day <- as.numeric(as.Date('2016-10-01') - as.Date('2016-08-01'))
targeted_end_day <- as.numeric(as.Date('2017-02-20') - as.Date('2016-08-01'))
targeted_days <- which(ts$day >= targeted_start_day & ts$day <= targeted_end_day) # index of days to target

EVI <- ts$EVI[targeted_days]
t <- ts$day[targeted_days]

model <- harmonic.regression(EVI, t/(2*3.14))
plot(t, EVI)
lines(t, EVI, col = "green")
lines(t, model$fit.vals, col = "red")

# get fitted parameters
phi <- model$pars$phi # phase in radians

# calculate peak and quarter period to compare to GEE estimate
period <- 150 # THIS IS GUESSED
peak_after_2016_08_01 <- period*(phi/(2*3.14)) #+ t[1] - as.numeric(as.Date('2016-08-01') - as.Date('2015-08-01'))
print('peak after 2016-08-01, R harmonic, Clinton')
print(peak_after_2016_08_01)

a <- model$coeffs[2]
b <- model$coeffs[3]

w <- ((3.14/2) + atan(-a/b))/peak_after_2016_08_01
quarter_period <- 3.14/(2*w)

print('w')
print(w)

print('quarter period')
print(quarter_period)

```